import type { Lesson } from '@/types/lesson';

export const s1_02: Lesson = {
  id: 's1-02',
  slug: 'make-your-first-beat',
  season: 1,
  index: 2,
  title: '你的第一個 30 分鐘',
  outcome: '一段自己錄、自己切、自己彈出來的兩小節循環',
  minutes: 30,
  chapters: ['認識機器', '錄進來', '切開它', '變成節奏'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s1-01'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：功能名稱與規格數字',
    '操作流程為實機實測後自行撰寫',
  ],
  videos: [
    {
      youtubeId: '1wt1Vx3-_0k',
      title: 'Akai MPC SAMPLE // Does it BEAT the Competition? + 5 Power Tips',
      channel: 'loopop',
      why: '評測與教學合一，標題註明含五個實用技巧。適合做完本課之後看一遍建立全貌。',
      lang: 'en',
      reviewed: false,
    },
    {
      youtubeId: 'b2MUQo3AFaI',
      title: 'MPC SAMPLE FULL TUTORIAL',
      channel: 'Tubedigga',
      why: '標題為完整教學。想一次看完全部功能、而不是照課程一步一步走的人可以先看它。',
      lang: 'en',
      reviewed: false,
    },
  ],
  checkpoints: [
    '你手上有一段兩小節、自己彈出來的循環',
    '那段循環已經 resample 收成一顆 pad',
    '專案已經用你自己取的名字存過一次',
    '你知道按住 SHIFT 之後，面板紅字代表什麼',
  ],
  steps: [
    // ── 第 1 段 · 認識機器 ──────────────────────────────
    {
      ch: 0,
      say: '電源鍵在<b>機器背面最右邊</b>。旁邊那個 USB-C 孔負責充電、傳音訊、也傳 MIDI。之後很多事都靠它。現在按下 <b>POWER</b> 開機。',
      targets: ['r_power', 'r_usb'],
      screen: { t1: 'BOOTING…', tabs: ['', '', ''], bots: ['', '', ''] },
      hear: '—',
    },
    {
      ch: 0,
      say: '開機後機器會自動載入示範專案。先把 <b>MAIN VOLUME</b> 轉到一半左右。',
      targets: ['vol'],
      screen: { t1: 'DEMO PROJECT loaded' },
      hear: '還沒有聲音',
    },
    {
      ch: 0,
      say: '按 <b>PLAY</b>，右下角綠色那顆。這是機器內建的示範節奏。先聽聽它能做到什麼程度。',
      targets: ['play'],
      screen: { t1: 'SEQ 01  ▶  90 BPM' },
      hear: '一段完整的鼓組節奏，pad 會跟著亮',
    },
    {
      ch: 0,
      say: '按 <b>STOP</b> 停下來，在 PLAY 左邊。記一個急救招式：<b>快速連按兩下 STOP</b>，所有聲音立刻消失。',
      targets: ['stop'],
      screen: { t1: 'SEQ 01  ■  90 BPM' },
      hear: '安靜',
    },
    {
      ch: 0,
      say: '現在隨便敲中間的 <b>pad</b>。每一顆是一個獨立的聲音。敲越用力越大聲。',
      targets: ['pads'],
      screen: { t1: 'PAD 05  KICK 02' },
      hear: '每敲一下出一個聲音',
    },
    {
      ch: 0,
      say: '按左上角的 <b>SAMPLE</b>，藍色那顆。這是主畫面，你之後八成時間都待在這裡。迷路了就按它回來。',
      targets: ['sample'],
      screen: { t1: 'A01 Kick 02' },
      hear: '—',
    },
    {
      ch: 0,
      say: '整台機器的邏輯只有一句話。<b>上方三顆 B 鍵換頁</b>，<b>中間三顆 K 旋鈕調參數</b>。螢幕上排的 Trim、Tune、Filter 就是 B1、B2、B3。下排的 Start、End、Loop 就是 K1、K2、K3。',
      targets: ['b1', 'b2', 'b3', 'k1', 'k2', 'k3'],
      screen: { t1: 'A01 Kick 02' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '整台機器只有這一個邏輯',
        body: '按鍵下方的紅色小字，是按住 SHIFT 之後的第二功能。下一步你就會用到。',
      },
    },

    // ── 第 2 段 · 錄進來 ────────────────────────────────
    {
      ch: 1,
      say: '按住左下角的 <b>SHIFT</b> 不放，再按 <b>SAMPLE</b>。看到 SAMPLE 下面那行紅字 INPUT CONFIG 亮起來了嗎？整個面板的紅字現在都亮了。那就是 SHIFT 的世界。',
      targets: ['sample'],
      shift: true,
      screen: { t1: 'INPUT CONFIG', tabs: ['Source', 'Monitor', 'Thresh'], bots: ['', '', ''] },
      hear: '—',
    },
    {
      ch: 1,
      say: '轉 <b>K1</b>，把 Source 選成 <b>Mic</b>。麥克風在右邊 ENCODER 旁邊那個小圖示的位置。',
      targets: ['k1', 'mic'],
      screen: { t1: 'SOURCE   MIC', tabs: ['Source', 'Monitor', 'Thresh'], bots: ['Mic', 'Auto', 'Off'] },
      hear: '—',
      note: {
        kind: 'tip',
        title: '正常現象',
        body: '選 Mic 之後內建喇叭會自動關掉。這是防止回授，不是故障。',
      },
    },
    {
      ch: 1,
      say: '按右下角紅色的 <b>SAMPLE RECORD</b> 進入錄音模式。再轉 <b>K2</b> 把 Rec Length 選成 <b>Free</b>，想錄多久就多久。',
      targets: ['srec', 'k2'],
      screen: { t1: 'REC READY', tabs: ['Source', 'Length', 'Thresh'], bots: ['Mic', 'Free', 'Off'] },
      hear: '—',
    },
    {
      ch: 1,
      say: '敲 <b>PAD 9</b> 開始錄。對著機器連續敲四下桌子，或哼四拍。<b>不要停頓</b>，節奏穩一點。',
      targets: ['p9'],
      screen: { t1: '● RECORDING  00:03', tabs: ['', '', ''], bots: ['', '', ''] },
      hear: '右邊音量表會跳動',
    },
    {
      ch: 1,
      say: '再敲一次 <b>PAD 9</b> 結束錄音。你剛剛錄的東西，現在住在那顆 pad 裡面了。',
      targets: ['p9'],
      screen: { t1: 'SAMPLE SAVED → PAD 09', tabs: ['', '', ''], bots: ['', '', ''] },
      hear: '—',
    },
    {
      ch: 1,
      say: '按 <b>SAMPLE</b> 回主畫面，再敲一次 <b>PAD 9</b>。螢幕上那條黃色波形，就是你自己的聲音。',
      targets: ['sample', 'p9'],
      screen: { t1: 'A09 My Rec 001', wave: 31 },
      hear: '你剛剛錄的聲音',
      note: {
        kind: 'win',
        title: '里程碑',
        body: '這個聲音的權利 100% 是你的。之後不管你拿它做什麼、賣給誰，都不會有人來找你。',
      },
    },

    // ── 第 3 段 · 切開它 ────────────────────────────────
    {
      ch: 2,
      say: '錄音頭尾一定有多餘空白。轉 <b>K1</b> 調 Start 起點，轉 <b>K2</b> 調 End 終點，把空白切掉。邊轉邊敲 pad 試聽。',
      targets: ['k1', 'k2'],
      screen: { t1: 'A09 My Rec 001', wave: 31 },
      hear: '頭尾的雜音消失',
    },
    {
      ch: 2,
      say: '切不準？<b>按住 SHIFT 再轉 K1 或 K2</b>，波形會放大。這個功能面板上沒印，快速指南也沒寫。但沒有它就切不準。',
      targets: ['k1', 'k2'],
      shift: true,
      screen: { t1: 'ZOOM ×8', wave: 31 },
      hear: '—',
      note: {
        kind: 'tip',
        title: '隱藏功能',
        body: 'SHIFT + K1 放大起點。SHIFT + K2 放大終點。SHIFT + K3 放大循環點。',
      },
    },
    {
      ch: 2,
      say: '錄太小聲的話，<b>按住 SHIFT 再按 B2</b>，也就是 Normalize。機器會把音量推到最大而不破音。',
      targets: ['b2'],
      shift: true,
      screen: { t1: 'NORMALIZE → 0 dB', wave: 88 },
      hear: '同一個聲音，變大聲了',
    },
    {
      ch: 2,
      say: '有趣的來了。按 <b>CHOP</b>，右上角藍色那顆。機器會把這段聲音切開，分配到 16 顆 pad 上。',
      targets: ['chop'],
      screen: { t1: 'CHOP  8 slices', tabs: ['Chop', 'Tune', 'Filter'], bots: ['Start', 'End', 'Type'], wave: 52 },
      hear: '—',
    },
    {
      ch: 2,
      say: '轉 <b>K3</b> 選切法。先選 <b>Regions 8</b>，不管內容，平均切成八塊。',
      targets: ['k3'],
      screen: { t1: 'CHOP TYPE  REG 8', tabs: ['Chop', 'Tune', 'Filter'], bots: ['Start', 'End', 'Reg8'], wave: 52 },
      hear: '—',
    },
    {
      ch: 2,
      say: '敲 <b>PAD 1 到 PAD 8</b>，每一顆是一塊。<b>刻意不要照順序</b>：5、2、5、8、1、1、7。你剛剛把自己的錄音重組成新東西了。',
      targets: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8'],
      screen: { t1: 'SLICE 05 / 08', tabs: ['Chop', 'Tune', 'Filter'], bots: ['Start', 'End', 'Reg8'], wave: 52 },
      hear: '原本的聲音，順序全變了',
      note: {
        kind: 'tip',
        title: '這就是取樣的核心',
        body: '你沒有創造新的聲音，你創造了新的順序。這件事從 1988 年做到現在都沒變。',
      },
    },
    {
      ch: 2,
      say: '某一塊特別好聽？<b>按住 SHIFT 再按 B1</b>，也就是 Extract。它會變成獨立樣本，跑到下一顆空 pad。之後可以單獨調音、單獨加效果。',
      targets: ['b1'],
      shift: true,
      screen: { t1: 'EXTRACT → PAD 10', tabs: ['Chop', 'Tune', 'Filter'], bots: ['', '', ''], wave: 52 },
      hear: '—',
      note: {
        kind: 'warn',
        title: '小心',
        body: '切片編輯不能用 Undo 復原。動手前先存一次專案比較保險。',
      },
    },

    // ── 第 4 段 · 變成節奏 ──────────────────────────────
    {
      ch: 3,
      say: '按 <b>SEQ</b>，在 SAMPLE 右邊。現在 pad 不是用來發聲，而是用來選段落。亮的代表裡面有東西。',
      targets: ['seq'],
      screen: { t1: 'SEQ 02  EMPTY', tabs: ['Seq', 'BPM', 'Rec Q'], bots: ['2 bars', '90.0', 'ON'] },
      hear: '—',
    },
    {
      ch: 3,
      say: '轉 <b>K1</b> 把長度設成 <b>2 小節</b>。再按 <b>B3</b> 把錄音量化打開。你敲歪的音會自動貼到格子上。',
      targets: ['k1', 'b3'],
      screen: { t1: 'LENGTH 2   Q 1/16', tabs: ['Seq', 'BPM', 'Rec Q'], bots: ['2 bars', '90.0', 'ON'] },
      hear: '—',
      note: {
        kind: 'tip',
        title: '新手一定要開',
        body: '等手感練起來再關掉。那時候的不準才叫味道，現在的不準只是不準。',
      },
    },
    {
      ch: 3,
      say: '按 <b>SEQ RECORD</b>，紅色那顆。它會開始閃，代表準備好了。再按 <b>PLAY</b> 開始錄。',
      targets: ['qrec', 'play'],
      screen: { t1: '● REC   BAR 1/2', tabs: ['Seq', 'BPM', 'Rec Q'], bots: ['2 bars', '90.0', 'ON'] },
      hear: '節拍器與空拍',
    },
    {
      ch: 3,
      say: '敲你的切片 <b>pad</b>，把剛才那段順序彈出來。跑完一輪機器會自動轉成疊錄。你可以繼續加東西上去。',
      targets: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8'],
      screen: { t1: '● REC   BAR 2/2  OVERDUB', tabs: ['', '', ''], bots: ['', '', ''] },
      hear: '你彈的東西開始循環',
    },
    {
      ch: 3,
      say: '按 <b>STOP</b>。恭喜，你有一段完全屬於自己的循環了。',
      targets: ['stop'],
      screen: { t1: 'SEQ 02  ■  2 bars' },
      hear: '安靜',
    },
    {
      ch: 3,
      say: '最後兩步最重要。<b>按住 SHIFT 再按 PAD 11</b>，看 PAD 11 上面的紅字 RESAMPLE。機器會把整段循環收成一個聲音，放進你指定的空 pad。',
      targets: ['p11'],
      shift: true,
      screen: { t1: 'RESAMPLE SEQ → pad?', tabs: ['', '', ''], bots: ['', '', ''] },
      hear: '—',
      note: {
        kind: 'tip',
        title: '這是最重要的一招',
        body: '收成一顆 pad 之後，其他 15 顆就空出來了。你可以拿去做貝斯。這是這台機器做出多層次音樂的唯一方法。',
      },
    },
    {
      ch: 3,
      say: '<b>按住 SHIFT 再按 PAD 16</b>，也就是 PROJECT。選 Save Project，用 <b>ENCODER</b> 逐字打名字。機器雖然有背景自動存檔，但那只是暫存。<b>那不是備份</b>。',
      targets: ['p16', 'enc'],
      shift: true,
      screen: { t1: 'SAVE  MY_FIRST_BEAT', tabs: ['', '', ''], bots: ['', '', ''] },
      hear: '—',
      note: {
        kind: 'win',
        title: '第 1 課完成',
        body: '你會了開機、面板邏輯、麥克風錄音。也會了修剪、Zoom、Normalize。還有切片、重組、Extract。以及序列錄音、Resample、存檔。下一課去讀懂整個面板。',
      },
    },
  ],
};
