import type { Lesson } from '@/types/lesson';

export const s2_07: Lesson = {
  id: 's2-07',
  slug: 'extract-and-mute-groups',
  season: 2,
  index: 7,
  title: 'Extract 與 Mute Group',
  outcome: '一組互不打架的獨立切片',
  minutes: 25,
  chapters: ['把切片變成獨立樣本', 'Split 與 Merge', 'Mute Group 防打架'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s2-06'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Chop 模式 SHIFT+B1 為 Extract（非破壞性，原樣本保留，新樣本進下一顆可用的 pad）、SHIFT+B2 為 Split、SHIFT+B3 為 Merge、按住 ERASE 敲 pad 移除切片；Play 頁 K2 為 Mute Group，值為 Off 或 1–16，同組最後被彈的 pad 會讓同組其他聲音停止',
    '操作流程為實機實測後自行撰寫',
  ],
  checkpoints: [
    '你把至少一塊切片 Extract 成獨立樣本',
    '你知道 Extract 不會破壞原始樣本',
    '你替兩顆會打架的 pad 設了同一個 Mute Group',
    '你聽得出設定前後低頻不再互相干擾',
  ],
  steps: [
    {
      ch: 0,
      say: '切好之後，某一塊特別好用。<b>把它變成獨立樣本</b>，之後才能單獨處理。',
      targets: ['chop'],
      screen: { t1: 'CHOP  SLICE 03', wave: 52 },
      hear: '那一塊切片',
    },
    {
      ch: 0,
      say: '選中那一塊，<b>按住 SHIFT 再按 B1</b>，也就是 Extract。',
      targets: ['b1'],
      shift: true,
      screen: { t1: 'EXTRACT → PAD 10', tabs: ['Chop', 'Tune', 'Filter'], wave: 52 },
      hear: '—',
    },
    {
      ch: 0,
      say: '它會<b>自動跑到下一顆可用的 pad</b>。這是非破壞性的，原始樣本完全不動。',
      targets: ['p10'],
      screen: { t1: 'A10 Slice 03', wave: 44 },
      hear: '獨立出來的那一塊',
      note: {
        kind: 'tip',
        title: '為什麼要 Extract',
        body: '獨立之後才能單獨調音、單獨加濾波、單獨設 Mute Group。切片做不到。',
      },
    },
    {
      ch: 1,
      say: '切片太長？<b>按住 SHIFT 再按 B2</b> 是 Split，把它對半切成兩塊。',
      targets: ['b2'],
      shift: true,
      screen: { t1: 'SPLIT SLICE 03', wave: 52 },
      hear: '一塊變兩塊',
      note: {
        kind: 'warn',
        title: '編號會跟著變',
        body: 'Split 之後，後面所有切片的編號都會加一。記得重新聽一次。',
      },
    },
    {
      ch: 1,
      say: '切片太碎？<b>按住 SHIFT 再按 B3</b> 是 Merge，把它跟前一塊合併。',
      targets: ['b3'],
      shift: true,
      screen: { t1: 'MERGE SLICE 03', wave: 52 },
      hear: '兩塊變一塊',
    },
    {
      ch: 1,
      say: '不要的切片就<b>按住 ERASE 再敲那顆 pad</b>。它會併進前一塊。',
      targets: ['erase'],
      screen: { t1: 'REMOVE SLICE', wave: 52 },
      hear: '—',
    },
    {
      ch: 2,
      say: '現在處理打架問題。<b>兩個低頻聲音同時響，會互相抵消變得沒力</b>。',
      targets: ['p1', 'p10'],
      screen: { t1: 'LOW FREQ CLASH' },
      hear: '兩個低音疊在一起，反而變小聲',
    },
    {
      ch: 2,
      say: '解法是 <b>Mute Group</b>。在 Play 頁轉 <b>K2</b>，值可以設 Off 或 1 到 16。',
      targets: ['k2'],
      screen: { t1: 'MUTE GROUP   1', tabs: ['Play', '', ''], bots: ['', 'Group', ''] },
      hear: '—',
    },
    {
      ch: 2,
      say: '<b>同一組裡最後被彈的那顆，會讓其他的停下來</b>。一次只響一個。',
      targets: ['p1', 'p10'],
      screen: { t1: 'MUTE GROUP   1' },
      hear: '後彈的把先彈的切掉',
    },
    {
      ch: 2,
      say: '最經典的例子是 hi-hat。<b>把閉合與開放設成同一組</b>，就像真的踩踏板。',
      targets: ['p3', 'p4'],
      screen: { t1: 'MUTE GROUP   2' },
      hear: '閉合 hat 一敲，開放 hat 立刻收掉',
      note: {
        kind: 'tip',
        title: '這是最像真人的一個設定',
        body: '真的鼓手沒辦法同時踩開跟踩合。設了 Mute Group，機器就懂這件事。',
      },
    },
    {
      ch: 2,
      say: '<b>低頻的東西都設同一組</b>：大鼓、貝斯、808。它們本來就不該同時響。',
      targets: ['p1', 'p13'],
      screen: { t1: 'MUTE GROUP   3' },
      hear: '低頻乾淨，不再互相抵消',
      note: {
        kind: 'win',
        title: '第 7 課完成',
        body: '設完 Mute Group 你會覺得整段突然變乾淨。那不是錯覺，是相位不再打架了。',
      },
    },
  ],
};
