import type { Lesson } from '@/types/lesson';

export const s2_06: Lesson = {
  id: 's2-06',
  slug: 'three-ways-to-chop',
  season: 2,
  index: 6,
  title: 'Chop 三種切法',
  outcome: '同一段素材用三種切法切出來的結果',
  minutes: 30,
  chapters: ['先存檔', 'Threshold 自動切', 'Regions 平均切', 'Manual 手動切'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s2-03'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Chop 頁 K3 為 Chop Type，含 Threshold／Regions 4、8、16／Manual；SHIFT+K3 調 Threshold 值 0–100%，值越高切片越少；Manual 模式敲 PAD 1 開始並加入起點，每個樣本最多 16 個切片；編輯切片會自動把 Chop Type 設成 Manual 且無法復原',
    '操作流程為實機實測後自行撰寫',
  ],
  checkpoints: [
    '你在切之前存過專案',
    '三種切法你都試過一次',
    '你知道 Threshold 值越高切片越少',
    '你知道切片編輯不能復原',
  ],
  steps: [
    {
      ch: 0,
      say: '動手之前先做一件事。<b>按住 SHIFT 再按 PAD 16</b> 存專案。',
      targets: ['p16'],
      shift: true,
      screen: { t1: 'SAVE PROJECT' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '切片編輯不能復原',
        body: 'UNDO 對切片編輯無效。切壞了只能重新載入專案，所以一定要先存。',
      },
    },
    {
      ch: 0,
      say: '敲要切的那顆 <b>pad</b>，按 <b>CHOP</b> 進入切片模式。',
      targets: ['chop'],
      screen: { t1: 'CHOP', tabs: ['Chop', 'Tune', 'Filter'], bots: ['Start', 'End', 'Type'], wave: 52 },
      hear: '—',
    },
    {
      ch: 0,
      say: '注意螢幕下排。<b>第三個字從 Loop 變成 Type</b>，那就是切法。',
      targets: ['k3'],
      screen: { t1: 'CHOP', bots: ['Start', 'End', 'Type'], wave: 52 },
      hear: '—',
    },
    {
      ch: 1,
      say: '<b>Threshold 是預設值</b>。它依音量自動找切點，聲音大的地方就切一刀。',
      targets: ['k3'],
      screen: { t1: 'CHOP TYPE   THRESHOLD', bots: ['Start', 'End', 'Thresh'], wave: 52 },
      hear: '—',
    },
    {
      ch: 1,
      say: '<b>按住 SHIFT 再轉 K3</b> 調 Threshold 值。<b>值越高，切片越少</b>。',
      targets: ['k3'],
      shift: true,
      screen: { t1: 'THRESHOLD   60%', bots: ['Start', 'End', 'Thresh'], wave: 52 },
      hear: '—',
      note: {
        kind: 'tip',
        title: '鼓循環先試這個',
        body: '鼓的音量起伏明顯，Threshold 通常一次就切在對的位置上。',
      },
    },
    {
      ch: 1,
      say: '敲 <b>PAD 1 到 PAD 8</b> 聽切出來的結果。切點不對就回去調數值再切一次。',
      targets: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8'],
      screen: { t1: 'SLICE 03 / 08', wave: 52 },
      hear: '一塊一塊的鼓聲',
    },
    {
      ch: 2,
      say: '轉 <b>K3</b> 換成 <b>Regions 4</b>。它不管內容，直接平均切成四塊。',
      targets: ['k3'],
      screen: { t1: 'CHOP TYPE   REG 4', bots: ['Start', 'End', 'Reg4'], wave: 52 },
      hear: '四塊等長的段落',
    },
    {
      ch: 2,
      say: '還有 <b>Regions 8</b> 與 <b>Regions 16</b>。<b>素材本身節奏很準時最好用</b>。',
      targets: ['k3'],
      screen: { t1: 'CHOP TYPE   REG 16', bots: ['Start', 'End', 'Reg16'], wave: 52 },
      hear: '十六塊等長的小段',
      note: {
        kind: 'tip',
        title: '怎麼選數字',
        body: '一小節四拍就切 4，想切到十六分音符就切 16。跟著拍子選。',
      },
    },
    {
      ch: 3,
      say: '轉 <b>K3</b> 換成 <b>Manual</b>。這是最準但最花時間的一種。',
      targets: ['k3'],
      screen: { t1: 'CHOP TYPE   MANUAL', bots: ['Start', 'End', 'Manual'], wave: 52 },
      hear: '—',
    },
    {
      ch: 3,
      say: '敲 <b>PAD 1</b> 開始播放並放下第一個切點。<b>播放中每敲一次 pad 就加一個切點</b>。',
      targets: ['p1'],
      screen: { t1: 'MANUAL   SLICE 1', wave: 52 },
      hear: '樣本從頭播放',
    },
    {
      ch: 3,
      say: '<b>每個樣本最多十六個切片</b>。跟著聽到的重音敲，比看波形準。',
      targets: ['p2', 'p3', 'p4', 'p5'],
      screen: { t1: 'MANUAL   SLICE 5', wave: 52 },
      hear: '切點跟著你的手落下',
    },
    {
      ch: 3,
      say: '轉 <b>K1</b> 與 <b>K2</b> 微調每一塊的頭尾。<b>SHIFT 加 K1 或 K2 可以放大</b>。',
      targets: ['k1', 'k2'],
      shift: true,
      screen: { t1: 'ZOOM  SLICE 3', wave: 52 },
      hear: '切點變乾淨',
      note: {
        kind: 'win',
        title: '第 6 課完成',
        body: '只要你動手改過切點，Chop Type 就會自動變成 Manual。這是正常的。',
      },
    },
  ],
};
