import type { Lesson } from '@/types/lesson';

export const s2_08: Lesson = {
  id: 's2-08',
  slug: 'build-your-sample-library',
  season: 2,
  index: 8,
  title: '建立你自己的素材庫',
  outcome: '一套三個月後你還找得到的素材命名與備份',
  minutes: 20,
  chapters: ['命名規範', '存單一樣本', '搬到記憶卡', '備份習慣'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s2-07'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：SHIFT + SAMPLE SEL 為 Save Sample；Project 選單的 SD Card Access 會把 microSD 掛載成電腦的外接磁碟，手冊註明 microSD 不含在盒裝內',
    '命名與備份規範為本站整理',
  ],
  checkpoints: [
    '你有一套固定的命名格式',
    '你單獨存過至少一個樣本',
    '你把素材傳到電腦或記憶卡備份過',
    '你的素材來源全部符合 2-2 的四種乾淨來源',
  ],
  steps: [
    {
      ch: 0,
      say: '素材庫的價值不在數量，在<b>三個月後你還找得到</b>。',
      targets: ['ssel'],
      screen: { t1: 'SAMPLE SELECT' },
      hear: '—',
    },
    {
      ch: 0,
      say: '建議格式：<b>類型加特徵加編號</b>。例如 kick_soft_01、vox_chop_03。',
      targets: ['enc'],
      screen: { t1: 'KICK_SOFT_01' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '為什麼類型放前面',
        body: '這樣同類型的會排在一起。找大鼓的時候，全部大鼓都在同一區。',
      },
    },
    {
      ch: 0,
      say: '<b>不要用中文、不要用空格</b>。有些系統讀不到，之後傳檔會出問題。',
      targets: ['enc'],
      screen: { t1: 'USE ASCII ONLY' },
      hear: '—',
    },
    {
      ch: 0,
      say: '自錄的素材<b>在名字裡標記來源</b>，例如 mic_keys_01。之後要證明來源很方便。',
      targets: ['mic'],
      screen: { t1: 'MIC_KEYS_01' },
      hear: '—',
      note: {
        kind: 'warn',
        title: 'CC0 素材要另外存證',
        body: '把授權頁面截圖，跟素材放在同一個資料夾。三年後你不會記得從哪抓的。',
      },
    },
    {
      ch: 1,
      say: '好用的素材要單獨存下來。<b>按住 SHIFT 再按 SAMPLE SEL</b>，也就是 Save Sample。',
      targets: ['ssel'],
      shift: true,
      screen: { t1: 'SAVE SAMPLE' },
      hear: '—',
    },
    {
      ch: 1,
      say: '<b>存專案不等於存樣本</b>。單獨存下來的樣本，別的專案才能載入使用。',
      targets: ['ssel'],
      shift: true,
      screen: { t1: 'SAVE SAMPLE' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '什麼樣的值得單獨存',
        body: '你花時間切乾淨、調好音的那些。隨手錄的實驗品不用。',
      },
    },
    {
      ch: 2,
      say: '要搬到電腦就<b>按住 SHIFT 再按 PAD 16</b> 進 Project。在裡面選 <b>SD Card Access</b>。',
      targets: ['p16'],
      shift: true,
      screen: { t1: 'SD CARD ACCESS' },
      hear: '—',
    },
    {
      ch: 2,
      say: '用 USB-C 接電腦，<b>記憶卡會變成一個外接磁碟</b>，直接拖拉檔案。',
      targets: ['r_usb'],
      screen: { t1: 'SD CARD ACCESS' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '記憶卡不含在盒裝內',
        body: '官方手冊明寫 microSD 要自己買。沒有卡就沒有這條傳檔路徑。',
      },
    },
    {
      ch: 2,
      say: '電腦上開<b>三個資料夾就好</b>：drums、melodic、texture。分太細你不會維護。',
      targets: ['r_usb'],
      screen: { t1: '3 FOLDERS' },
      hear: '—',
    },
    {
      ch: 3,
      say: '傳完<b>先在電腦上安全退出磁碟</b>，再按 <b>B1</b> 離開這個模式。',
      targets: ['b1'],
      screen: { t1: 'SD CARD ACCESS' },
      hear: '—',
    },
    {
      ch: 3,
      say: '備份規則只有一條：<b>只存在一個地方的東西，等於沒有備份</b>。',
      targets: ['r_usb'],
      screen: { t1: 'BACKUP' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '背景自動存檔救不了你',
        body: '那只是暫存。卡壞了、機器摔了，沒有第二份就是全沒了。',
      },
    },
    {
      ch: 3,
      say: '養成習慣：<b>每次做完一首歌，就把新素材傳一次出去</b>。',
      targets: ['p16'],
      shift: true,
      screen: { t1: 'SAVE PROJECT' },
      hear: '—',
      note: {
        kind: 'win',
        title: '第 2 季完成',
        body: '你有一組乾淨、命名清楚、備份好的素材了。下一季把它們變成一首歌。',
      },
    },
  ],
};
