import type { Lesson } from '@/types/lesson';

export const s2_04: Lesson = {
  id: 's2-04',
  slug: 'lowpass-filter-drums-and-bass',
  season: 2,
  index: 4,
  title: '低通濾波留下鼓與貝斯',
  outcome: '一段只剩低頻的節奏底層',
  minutes: 20,
  chapters: ['先講清楚做得到什麼', 'Cutoff 怎麼轉', 'Reso 與濾波型式'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s2-03'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Sample 頁 Filter 的 K1 Cutoff 0–127、K2 Reso 0–127、K3 Type 為 Off／Classic／LPF2／LPF4／HPF2／HPF4 等',
    '操作流程為實機實測後自行撰寫',
  ],
  checkpoints: [
    '你知道濾波不能真的分離樂器',
    '你用低通做出了只剩低頻的版本',
    '你聽得出 LPF2 與 LPF4 的差別',
    '你知道 Reso 開太大會怎樣',
  ],
  steps: [
    {
      ch: 0,
      say: '先誠實說一件事。<b>濾波不能把樂器分開</b>，它只是砍掉一段頻率。',
      targets: ['b3'],
      screen: { t1: 'FILTER', tabs: ['Trim', 'Tune', 'Filter'], bots: ['Cutoff', 'Reso', 'Type'], wave: 31 },
      hear: '—',
      note: {
        kind: 'warn',
        title: '這台沒有音軌分離',
        body: '它不能自動抽出人聲或鼓。頻率重疊的部分一定會一起被砍掉。',
      },
    },
    {
      ch: 0,
      say: '但它夠用。<b>鼓與貝斯的能量在低頻</b>，把高頻砍掉就剩下它們。',
      targets: ['b3'],
      screen: { t1: 'FILTER', wave: 31 },
      hear: '—',
    },
    {
      ch: 1,
      say: '在 SAMPLE 頁按 <b>B3</b> 到 Filter。轉 <b>K3</b> 先把 Type 選成 <b>LPF2</b>。',
      targets: ['b3', 'k3'],
      screen: { t1: 'TYPE   LPF2', tabs: ['Trim', 'Tune', 'Filter'], bots: ['Cutoff', 'Reso', 'Type'], wave: 31 },
      hear: '—',
    },
    {
      ch: 1,
      say: '轉 <b>K1</b> 的 <b>Cutoff</b>，範圍是 0 到 127。<b>往下轉，高頻一點一點消失</b>。',
      targets: ['k1'],
      screen: { t1: 'CUTOFF   64', bots: ['Cutoff', 'Reso', 'Type'] },
      hear: '鈸與高頻樂器逐漸不見',
    },
    {
      ch: 1,
      say: '<b>邊轉邊敲 pad 試聽</b>。轉到人聲與吉他變糊，但大鼓還清楚的位置。',
      targets: ['k1', 'p1'],
      screen: { t1: 'CUTOFF   40' },
      hear: '只剩鼓與貝斯的悶悶版本',
      note: {
        kind: 'tip',
        title: '找那個剛剛好的點',
        body: '砍太多大鼓也會變沒力。留一點中頻，節奏才有輪廓。',
      },
    },
    {
      ch: 2,
      say: '轉 <b>K2</b> 的 <b>Reso</b>。它在截止點附近做一個突起，讓濾波有個性。',
      targets: ['k2'],
      screen: { t1: 'RESO   20', bots: ['Cutoff', 'Reso', 'Type'] },
      hear: '截止點附近變得突出',
    },
    {
      ch: 2,
      say: '<b>Reso 開太大會嘯叫</b>。做節奏底層通常開一點點就好，甚至不開。',
      targets: ['k2'],
      screen: { t1: 'RESO   0' },
      hear: '乾淨的低通，沒有尖銳的共振',
      note: {
        kind: 'warn',
        title: '什麼時候才開大',
        body: '要做濾波掃動的效果時才開大。做素材底層開大只會刺耳。',
      },
    },
    {
      ch: 2,
      say: '轉 <b>K3</b> 比較 <b>LPF2</b> 與 <b>LPF4</b>。數字大的砍得比較陡。',
      targets: ['k3'],
      screen: { t1: 'TYPE   LPF4', bots: ['Cutoff', 'Reso', 'Type'] },
      hear: 'LPF4 高頻消失得更乾脆',
    },
    {
      ch: 2,
      say: '<b>Classic 是另一種味道</b>，不那麼乾淨但比較有感情。試試看再決定。',
      targets: ['k3'],
      screen: { t1: 'TYPE   CLASSIC' },
      hear: '比較溫暖、比較不精準',
    },
    {
      ch: 2,
      say: '滿意就<b>按住 SHIFT 再按 PAD 11</b> 收成新樣本，原本那顆留著備用。',
      targets: ['p11'],
      shift: true,
      screen: { t1: 'RESAMPLE' },
      hear: '—',
      note: {
        kind: 'win',
        title: '第 4 課完成',
        body: '你有了節奏底層。下一課反過來，把低頻砍掉讓人聲浮出來。',
      },
    },
  ],
};
