import type { Lesson } from '@/types/lesson';

export const s2_03: Lesson = {
  id: 's2-03',
  slug: 'find-the-drum-break',
  season: 2,
  index: 3,
  title: '找到「只有鼓」的那四小節',
  outcome: '一段沒有其他樂器蓋住的乾淨鼓循環',
  minutes: 25,
  chapters: ['為什麼先找不用切', '三個最容易找到的位置', '切乾淨', '對齊速度'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s2-02'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Trim 頁 K1 Start／K2 End、SHIFT+K1／K2 為 Zoom、SHIFT+B2 為 Normalize、Tune 頁 K3 Warp 為 Off／50–200%／Seq',
    '取樣手法為本站整理',
  ],
  checkpoints: [
    '你手上有一段只有鼓的循環',
    '那段的頭尾都切乾淨了',
    '你知道要先找乾淨段落，再考慮濾波',
    '素材來源符合 2-2 的四種乾淨來源',
  ],
  steps: [
    {
      ch: 0,
      say: '這一課排在濾波前面是<b>刻意的</b>。先找本來就乾淨的段落，效果最好。',
      targets: ['pads'],
      screen: { t1: 'SAMPLE', wave: 31 },
      hear: '—',
      note: {
        kind: 'warn',
        title: '濾波不是萬能',
        body: '濾波是不得已才用的。原本就分離的段落，永遠比濾出來的乾淨。',
      },
    },
    {
      ch: 0,
      say: '素材先確認來源。<b>自錄、機器內建、CC0、付費素材包</b>，四種之一才動手。',
      targets: ['mic'],
      screen: { t1: 'SOURCE   MIC' },
      hear: '—',
    },
    {
      ch: 1,
      say: '第一個位置：<b>前奏</b>。很多錄音開頭幾小節只有鼓，其他樂器還沒進來。',
      targets: ['k1'],
      screen: { t1: 'A01 My Rec', wave: 31 },
      hear: '開頭只有鼓的段落',
    },
    {
      ch: 1,
      say: '第二個位置：<b>間奏</b>。主唱休息、樂器變少的那幾小節。',
      targets: ['k1', 'k2'],
      screen: { t1: 'A01 My Rec', wave: 52 },
      hear: '中段樂器變少',
    },
    {
      ch: 1,
      say: '第三個位置：<b>breakdown</b>。副歌前刻意把東西拿光的那一段。',
      targets: ['k1', 'k2'],
      screen: { t1: 'A01 My Rec', wave: 52 },
      hear: '只剩鼓與空間',
      note: {
        kind: 'tip',
        title: '找的時候閉上眼睛',
        body: '不要看波形找。用耳朵聽哪裡樂器最少，波形只是後續的工具。',
      },
    },
    {
      ch: 2,
      say: '找到之後回 <b>SAMPLE</b> 頁。轉 <b>K1</b> 調 Start，轉 <b>K2</b> 調 End，框住那一段。',
      targets: ['k1', 'k2'],
      screen: { t1: 'A01 My Rec', tabs: ['Trim', 'Tune', 'Filter'], bots: ['Start', 'End', 'Loop'], wave: 31 },
      hear: '框選範圍內的聲音',
    },
    {
      ch: 2,
      say: '切不準就<b>按住 SHIFT 再轉 K1 或 K2</b> 放大波形。切鼓一定要放大。',
      targets: ['k1', 'k2'],
      shift: true,
      screen: { t1: 'ZOOM ×8', wave: 31 },
      hear: '—',
    },
    {
      ch: 2,
      say: '起點要卡在<b>大鼓的最前緣</b>。切太早會有雜音，切太晚大鼓的頭會被削掉。',
      targets: ['k1'],
      shift: true,
      screen: { t1: 'START  ZOOM', wave: 31 },
      hear: '乾淨俐落的第一下',
    },
    {
      ch: 2,
      say: '太小聲就<b>按住 SHIFT 再按 B2</b> 做 Normalize，音量推到最大而不破音。',
      targets: ['b2'],
      shift: true,
      screen: { t1: 'NORMALIZE → 0 dB', wave: 88 },
      hear: '同一段，變大聲了',
    },
    {
      ch: 3,
      say: '速度對不上就按 <b>B2</b> 到 Tune 頁，轉 <b>K3</b> 調 <b>Warp</b>。',
      targets: ['b2'],
      screen: { t1: 'TUNE', tabs: ['Trim', 'Tune', 'Filter'], bots: ['Semi', 'Fine', 'Warp'], wave: 31 },
      hear: '—',
    },
    {
      ch: 3,
      say: 'Warp 設 <b>50% 就是一半長、兩倍快</b>，<b>200% 就是兩倍長、一半慢</b>。',
      targets: ['k3'],
      screen: { t1: 'WARP   120%', bots: ['Semi', 'Fine', 'Warp'] },
      hear: '長度改變',
    },
    {
      ch: 3,
      say: '<b>按住 SHIFT 再按 PAD 15</b> 切換 Warp 模式。Time Stretch 不動音高，Pitch 會一起變。',
      targets: ['p15'],
      shift: true,
      screen: { t1: 'WARP   TIME STRETCH' },
      hear: '同樣速度，音高不變',
      note: {
        kind: 'win',
        title: '第 3 課完成',
        body: '你手上有一段乾淨的鼓了。下一課才進入濾波，那是找不到乾淨段落時的備案。',
      },
    },
  ],
};
