import type { Lesson } from '@/types/lesson';

export const s2_01: Lesson = {
  id: 's2-01',
  slug: 'record-external-audio',
  season: 2,
  index: 1,
  title: '把外面的聲音抓進來',
  outcome: '一段從外部音源錄進 pad 的乾淨素材',
  minutes: 30,
  chapters: ['八個來源', '接上你的音源', '錄音前的四個設定', '開始錄', '錄完與救援'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-09',
  prerequisites: ['s1-01', 's1-02'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Input Configuration 的 Source 八個選項、Rec Length 的 FREE 與 SEQ、Rec Input Effects、Threshold；Sample Record 頁 K1 選來源、K3 調 Threshold、B1 切換 Monitor 三段；錄音以敲 pad 開始、錄音中可再敲 pad 切片、三種停止方式的差別；SHIFT + SAMPLE RECORD 撈回最後 25 秒',
    'Akai 官方使用手冊 v1.3.0 (RevA)：AUDIO IN 為 1/4" TRS 線路電平輸入，適用麥克風、樂器、混音器、合成器、鼓機；USB-C 可與電腦或行動裝置互傳音訊與 MIDI；接上耳機時內建喇叭停用',
    '唱盤需經唱頭放大器為一般音訊常識',
  ],
  checkpoints: [
    '你知道八個錄音來源分別是什麼',
    '你的音源已經正確接上，而且聽得到監聽',
    '你錄下了一段沒有破音的素材',
    '你知道三種停止錄音的方式差在哪',
    '你知道漏錄了可以用 Recall 救回來',
  ],
  steps: [
    // ── 第 1 段 · 八個來源 ──────────────────────────────
    {
      ch: 0,
      say: '<b>按住 SHIFT 再按 SAMPLE</b> 打開 Input Config。所有錄音來源都在這裡選。',
      targets: ['sample'],
      shift: true,
      screen: { t1: 'INPUT CONFIG', tabs: ['Source', 'Monitor', 'Thresh'], bots: ['Mic', 'Auto', 'Off'] },
      hear: '—',
    },
    {
      ch: 0,
      say: '轉 <b>K1</b> 看一遍，來源一共八個，分成三類。',
      targets: ['k1'],
      screen: { t1: 'SOURCE', tabs: ['Source', 'Monitor', 'Thresh'], bots: ['Mic', 'Auto', 'Off'] },
      hear: '—',
      note: {
        kind: 'tip',
        title: '八個來源',
        body: 'Mic 是內建麥克風。Rear、Rear L、Rear R 是背板類比輸入。USB、USB L、USB R 是數位。Resample 是錄機器自己。',
      },
    },
    {
      ch: 0,
      say: '<b>Rear 與 USB 是立體聲</b>，會同時收 1/L 與 2/R。加 L 或 R 就只收那一邊。',
      targets: ['k1'],
      screen: { t1: 'SOURCE   USB', bots: ['USB', 'Auto', 'Off'] },
      hear: '—',
    },

    // ── 第 2 段 · 接上你的音源 ──────────────────────────
    {
      ch: 1,
      say: '第一種接法，<b>手機或電腦走 USB-C</b>。訊號是數位的，不經過空氣也不經過線路。',
      targets: ['r_usb'],
      screen: { t1: 'SOURCE   USB' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '為什麼優先選 USB',
        body: '沒有環境噪音，也沒有線路底噪。同一段素材，數位錄出來就是比較乾淨。',
      },
    },
    {
      ch: 1,
      say: '接上之後把 Source 轉到 <b>USB</b>。<b>手機上放什麼，它就錄什麼</b>。',
      targets: ['r_usb'],
      screen: { t1: 'SOURCE   USB' },
      hear: '手機正在播的聲音',
      note: {
        kind: 'warn',
        title: '技術上做得到，法律上要先想清楚',
        body: '串流平台、影音網站、你自己的音樂檔，只要手機播得出來就錄得進來。但平台的服務條款本身就禁止錄製，那跟著作權是兩條各自獨立的責任線。動手前先看 2-2。',
      },
    },
    {
      ch: 1,
      say: '用<b>不能傳資料的充電線</b>會完全沒反應。線要選確定支援資料傳輸的。',
      targets: ['r_usb'],
      screen: { t1: 'SOURCE   USB' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '尚未驗證',
        body: '手機需不需要 OTG 或轉接器、電腦要不要裝驅動，我們還沒實測。官方影片見本頁下方。',
      },
    },
    {
      ch: 1,
      say: '第二種接法，<b>唱盤走背板 AUDIO IN</b>。但唱盤不能直接接，訊號太小。',
      targets: ['r_in1', 'r_in2'],
      screen: { t1: 'SOURCE   REAR' },
      hear: '直接接會非常小聲而且很悶',
      note: {
        kind: 'warn',
        title: '唱盤一定要先過唱頭放大器',
        body: '官方手冊寫 AUDIO IN 是給線路電平來源用的。唱盤輸出的 phono 訊號遠低於線路電平，高低頻也還沒還原。少了這一步，錄進來一定又小又悶。',
      },
    },
    {
      ch: 1,
      say: '正確接法：<b>唱盤 → 唱頭放大器或混音器 → 背板 AUDIO IN 1/L 與 2/R</b>。',
      targets: ['r_in1', 'r_in2'],
      screen: { t1: 'SOURCE   REAR' },
      hear: '音量正常、高低頻平衡的訊號',
      note: {
        kind: 'tip',
        title: '有些唱盤內建放大器',
        body: '看背後有沒有 PHONO／LINE 切換開關。切到 LINE 就可以直接接進來。',
      },
    },
    {
      ch: 1,
      say: '第三種，<b>混音器、樂器、效果器直接接</b>。它們輸出的就是線路電平，不用再放大。',
      targets: ['r_in1'],
      screen: { t1: 'SOURCE   REAR' },
      hear: '—',
    },
    {
      ch: 1,
      say: '走背板的話，轉 <b>REC GAIN</b> 調進來的音量。這一顆決定會不會破音。',
      targets: ['r_gain'],
      screen: { t1: 'SOURCE   REAR' },
      hear: '訊號變大或變小',
      note: {
        kind: 'tip',
        title: '官方寫得很明白',
        body: '手冊寫 AUDIO IN 是給線路電平來源用的。麥克風、樂器、混音器、合成器、鼓機都算。REC GAIN 調的就是這一路的錄音電平。',
      },
    },

    // ── 第 3 段 · 錄音前的四個設定 ──────────────────────
    {
      ch: 2,
      say: '按 <b>SAMPLE RECORD</b>（右下角紅色）進錄音頁。以下四個設定決定錄出來的品質。',
      targets: ['srec'],
      screen: { t1: 'REC READY', tabs: ['Monitor', 'Length', 'Thresh'], bots: ['USB', 'Free', 'Off'] },
      hear: '—',
    },
    {
      ch: 2,
      say: '設定一，轉 <b>K1</b> 選來源。這裡跟 Input Config 是同一個設定，改哪邊都一樣。',
      targets: ['k1'],
      screen: { t1: 'SOURCE   USB', bots: ['USB', 'Free', 'Off'] },
      hear: '—',
    },
    {
      ch: 2,
      say: '設定二，按 <b>B1</b> 切換監聽。三段循環：<b>Off</b>、<b>Auto</b>、<b>On</b>。',
      targets: ['b1'],
      screen: { t1: 'MONITOR   AUTO', tabs: ['Monitor', 'Length', 'Thresh'] },
      hear: '進來的聲音開始從機器出來',
      note: {
        kind: 'tip',
        title: '三段差在哪',
        body: 'Off 永遠不監聽。Auto 只在錄音頁時監聽。On 永遠監聽。先用 Auto 最安全。',
      },
    },
    {
      ch: 2,
      say: '螢幕上的<b>喇叭圖示被劃掉</b>，代表內建喇叭現在是關的。這是正常的防回授機制。',
      targets: ['vol'],
      screen: { t1: 'MONITOR   AUTO' },
      hear: '從耳機聽得到，喇叭沒聲音',
      note: {
        kind: 'tip',
        title: '什麼時候會被關掉',
        body: '選內建麥克風當來源、或背板接了耳機與輸出時，喇叭會自動關掉。插耳機監聽就好。',
      },
    },
    {
      ch: 2,
      say: '設定三，轉 <b>K2</b> 選 <b>Rec Length</b>。<b>FREE</b> 是想錄多久就多久。',
      targets: ['k2'],
      screen: { t1: 'LENGTH   FREE', bots: ['USB', 'Free', 'Off'] },
      hear: '—',
    },
    {
      ch: 2,
      say: '選 <b>SEQ</b> 則長度鎖定成序列長度。<b>播放中選 SEQ，會等目前循環結束才開始錄</b>。',
      targets: ['k2'],
      screen: { t1: 'LENGTH   SEQ', bots: ['USB', 'Seq', 'Off'] },
      hear: '—',
      note: {
        kind: 'tip',
        title: '什麼時候用 SEQ',
        body: '要錄剛好一段循環時用它，長度自動對齊，省掉修剪的工。',
      },
    },
    {
      ch: 2,
      say: '設定四，轉 <b>K3</b> 調 <b>Threshold</b>。訊號超過這個音量才會自動開始錄。',
      targets: ['k3'],
      screen: { t1: 'THRESHOLD  -24 dB', bots: ['USB', 'Free', '-24'] },
      hear: '—',
    },
    {
      ch: 2,
      say: '訊號一超過門檻，<b>螢幕右上角的波形圖示會亮起來</b>。用它確認訊號真的進來了。',
      targets: ['k3'],
      screen: { t1: 'SIGNAL OK', bots: ['USB', 'Free', '-24'] },
      hear: '音源的聲音',
      note: {
        kind: 'warn',
        title: '先確認再錄',
        body: '圖示不亮就代表訊號沒進來。這時候按下去只會錄到一片安靜。',
      },
    },

    // ── 第 4 段 · 開始錄 ────────────────────────────────
    {
      ch: 3,
      say: '設定好了就開錄。<b>敲你要放樣本的那顆空 pad</b>，錄音立刻開始。',
      targets: ['p9'],
      screen: { t1: '● RECORDING  00:03', tabs: ['', '', ''], bots: ['', '', ''] },
      hear: '你的音源，音量表跟著跳',
    },
    {
      ch: 3,
      say: '這裡有個很少人知道的招式。<b>錄音進行中，再敲其他 pad 就能當場切片</b>。',
      targets: ['p10', 'p11', 'p12'],
      screen: { t1: '● RECORDING  SLICE 3' },
      hear: '持續錄音中',
      note: {
        kind: 'tip',
        title: '邊錄邊切',
        body: '聽到想要的段落就敲一顆新 pad，切點當場就下好了。錄完不用再進 Chop。',
      },
    },
    {
      ch: 3,
      say: '停止有三種方式，<b>差別在停完之後你在哪裡</b>。',
      targets: ['srec', 'stop'],
      screen: { t1: '● RECORDING' },
      hear: '—',
    },
    {
      ch: 3,
      say: '按 <b>SAMPLE RECORD</b> 停止：<b>直接回到 Sample 模式</b>，而且新樣本已經選好了。',
      targets: ['srec'],
      screen: { t1: 'A09 My Rec 001', wave: 31 },
      hear: '—',
    },
    {
      ch: 3,
      say: '<b>再敲一次同一顆 pad</b>，或按 <b>STOP</b>：停止錄音但<b>留在錄音頁</b>，可以繼續錄下一段。',
      targets: ['p9', 'stop'],
      screen: { t1: 'REC READY', bots: ['USB', 'Free', '-24'] },
      hear: '安靜',
      note: {
        kind: 'tip',
        title: '要連錄好幾段就用這個',
        body: '一次抓好幾段素材時，用 pad 或 STOP 停，手不用離開錄音頁。',
      },
    },

    // ── 第 5 段 · 錄完與救援 ────────────────────────────
    {
      ch: 4,
      say: '漏錄了怎麼辦？<b>按住 SHIFT 再按 SAMPLE RECORD</b>，那是 RECALL。',
      targets: ['srec'],
      shift: true,
      screen: { t1: 'RECALL' },
      hear: '—',
    },
    {
      ch: 4,
      say: '它會把<b>剛剛過去的最後 25 秒</b>撈回來，自動放到下一顆可用的 pad。',
      targets: ['srec'],
      shift: true,
      screen: { t1: 'RECALL → PAD 10', wave: 44 },
      hear: '剛剛沒錄到的那一段',
      note: {
        kind: 'warn',
        title: '尚未驗證：25 或 30 秒',
        body: '官方手冊內文寫 25 秒，規格表寫 30 秒，同一份文件自相矛盾。實測前不寫死。',
      },
    },
    {
      ch: 4,
      say: '按 <b>SAMPLE</b> 回主畫面，轉 <b>K1</b> 與 <b>K2</b> 把頭尾修乾淨。切法看下一課。',
      targets: ['sample', 'k1', 'k2'],
      screen: { t1: 'A09 My Rec 001', tabs: ['Trim', 'Tune', 'Filter'], bots: ['Start', 'End', 'Loop'], wave: 31 },
      hear: '修剪後的素材',
    },
    {
      ch: 4,
      say: '最後一件事，<b>錄進來不等於可以用</b>。素材能不能用，下一課專門講。',
      targets: ['p16'],
      shift: true,
      screen: { t1: 'SAVE PROJECT' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '這一步不能跳過',
        body: '技術上你可以錄任何進得來的訊號。但能不能拿去用是另一件事，看 2-2。',
      },
    },
  ],
};
