import type { Lesson } from '@/types/lesson';

export const s2_05: Lesson = {
  id: 's2-05',
  slug: 'highpass-filter-for-vocals',
  season: 2,
  index: 5,
  title: '高通濾波讓人聲浮出來',
  outcome: '一段只剩中高頻的旋律素材',
  minutes: 20,
  chapters: ['反過來砍', '殘留是正常的', '把殘留變成味道'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s2-04'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Sample 頁 Filter 的 Type 含 HPF2 與 HPF4；Knob FX 的 Vinyl Emulator 與 Tape Emulator 參數',
    '操作流程為實機實測後自行撰寫',
  ],
  checkpoints: [
    '你做出了一段砍掉低頻的版本',
    '你聽得出殘留的鼓聲還在',
    '你知道殘留不是失敗，而是可以利用的質地',
  ],
  steps: [
    {
      ch: 0,
      say: '這一課跟上一課相反。<b>砍掉低頻，讓中高頻的東西浮上來</b>。',
      targets: ['b3'],
      screen: { t1: 'FILTER', tabs: ['Trim', 'Tune', 'Filter'], bots: ['Cutoff', 'Reso', 'Type'], wave: 52 },
      hear: '—',
    },
    {
      ch: 0,
      say: '在 Filter 頁轉 <b>K3</b>，把 Type 選成 <b>HPF2</b>。',
      targets: ['k3'],
      screen: { t1: 'TYPE   HPF2', bots: ['Cutoff', 'Reso', 'Type'] },
      hear: '—',
    },
    {
      ch: 0,
      say: '轉 <b>K1</b> 的 Cutoff 往上。<b>大鼓與貝斯會先消失</b>，人聲與旋律留下來。',
      targets: ['k1'],
      screen: { t1: 'CUTOFF   50', bots: ['Cutoff', 'Reso', 'Type'] },
      hear: '低頻退場，中高頻變清楚',
    },
    {
      ch: 0,
      say: '<b>轉到大鼓剛好聽不見就停</b>。再往上轉，人聲會變得又薄又假。',
      targets: ['k1'],
      screen: { t1: 'CUTOFF   45' },
      hear: '人聲清楚，低頻幾乎沒了',
      note: {
        kind: 'tip',
        title: '一個判斷方法',
        body: '用耳機聽。低頻的震動感消失、但人聲還有厚度，那就是對的位置。',
      },
    },
    {
      ch: 1,
      say: '你會發現<b>小鼓與鈸還在</b>。這很正常，它們的頻率跟人聲重疊。',
      targets: ['k1'],
      screen: { t1: 'CUTOFF   45' },
      hear: '人聲背後仍有小鼓與鈸',
      note: {
        kind: 'warn',
        title: '這不是你做錯',
        body: '任何濾波都做不到完全分離。重疊的頻率一定會一起留下來。',
      },
    },
    {
      ch: 1,
      say: '如果殘留的鼓聲會干擾，<b>回去換一段素材</b>比繼續調濾波有效。',
      targets: ['k1', 'k2'],
      screen: { t1: 'A01 My Rec', wave: 31 },
      hear: '—',
    },
    {
      ch: 2,
      say: '但殘留常常是好事。<b>那一層背景的鼓，就是 lo-fi 味道的來源</b>。',
      targets: ['knobfx'],
      screen: { t1: 'KNOB FX' },
      hear: '人聲加上一層模糊的節奏底',
    },
    {
      ch: 2,
      say: '把它推得更遠。選 <b>Vinyl Emulator</b>，轉 <b>K2</b> 的 Crackle 加一點雜訊。',
      targets: ['k2'],
      screen: { t1: 'VINYL EMULATOR', bots: ['Tone', 'Crackle', 'Pitch'] },
      hear: '像從舊唱片裡撈出來的一段',
    },
    {
      ch: 2,
      say: '或選 <b>Tape Emulator</b>，轉 <b>K1</b> 的 Wow 讓音高微微飄。',
      targets: ['k1'],
      screen: { t1: 'TAPE EMULATOR', bots: ['Wow', 'Noise', 'Pitch'] },
      hear: '音高輕輕晃動的舊味道',
    },
    {
      ch: 2,
      say: '滿意就 <b>SHIFT 加 PAD 11</b> 收成新樣本。原始素材永遠留著。',
      targets: ['p11'],
      shift: true,
      screen: { t1: 'RESAMPLE' },
      hear: '—',
      note: {
        kind: 'win',
        title: '第 5 課完成',
        body: '低通給你節奏，高通給你旋律。兩段素材疊起來就是一首歌的雛形。',
      },
    },
  ],
};
