import type { Lesson } from '@/types/lesson';

export const s3_07: Lesson = {
  id: 's3-07',
  slug: 'step-edit-and-swing',
  season: 3,
  index: 7,
  title: 'Step Edit 與 Swing',
  outcome: '一段聽起來像人彈的循環',
  minutes: 30,
  chapters: ['逐格檢查', '推桿是人味來源', 'Swing 與整體推移', '推桿還能做什麼'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s3-02'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Step Edit 的 K1 長度、K2 量化值、K3 力度、SHIFT+K2 拍號、推桿推移事件；Time Correct 的 K1 Q、K2 Shift、K3 Swing、B3 套用',
    '操作流程為實機實測後自行撰寫',
  ],
  checkpoints: [
    '你用 Step Edit 修掉了至少一個不想要的音',
    '你用推桿把某個音前後推移過',
    '你試過 Time Correct 的 Swing 並聽出差別',
    '你知道 Q 與 Swing 是全域設定',
  ],
  steps: [
    {
      ch: 0,
      say: '<b>按住 SHIFT 再按 SEQ</b> 進 Step Edit。這裡可以一格一格檢查已經錄好的音。',
      targets: ['seq'],
      shift: true,
      screen: { t1: 'STEP EDIT  BAR 1', tabs: ['Step', 'Q', 'Vel'], bots: ['Length', 'Q 1/16', 'Vel'] },
      hear: '—',
    },
    {
      ch: 0,
      say: '轉 <b>ENCODER</b> 一格一格前進。一次走多少由量化值決定。',
      targets: ['enc'],
      screen: { t1: 'STEP 03 / 32' },
      hear: '該格上的音',
    },
    {
      ch: 0,
      say: '同一格有好幾個音時，按 <b>−/＋</b> 切換，或直接<b>敲那顆 pad</b> 選它。',
      targets: ['minus', 'plus'],
      screen: { t1: 'STEP 03  EVENT 2/3' },
      hear: '被選中的那個音',
    },
    {
      ch: 0,
      say: '不要的音就按 <b>B3</b> 刪掉。這比重錄整段快得多。',
      targets: ['b3'],
      screen: { t1: 'ERASE EVENT' },
      hear: '那個音消失了',
    },
    {
      ch: 1,
      say: '這一課的重點來了。<b>把推桿往上或往下推</b>，選中的那個音會往前或往後移。',
      targets: ['fader'],
      screen: { t1: 'NUDGE  +3' },
      hear: '那一下的位置微微改變',
      note: {
        kind: 'tip',
        title: '這就是人味的來源',
        body: '真人不會每一下都準。小鼓晚個幾格，整段立刻像人彈的。',
      },
    },
    {
      ch: 1,
      say: '先試<b>小鼓晚一點</b>。往後推一點點就好，推太多會變成錯拍。',
      targets: ['fader'],
      screen: { t1: 'SNARE  NUDGE +2' },
      hear: '小鼓稍微拖了一點',
    },
    {
      ch: 1,
      say: '轉 <b>K3</b> 可以改選中那個音的<b>力度</b>。強弱不一樣，聽起來就不機械。',
      targets: ['k3'],
      screen: { t1: 'VELOCITY  96' },
      hear: '那一下變輕或變重',
    },
    {
      ch: 2,
      say: '整段一起處理用 Time Correct。<b>按住 SHIFT 再按 PAD 14</b>。',
      targets: ['p14'],
      shift: true,
      screen: { t1: 'TIME CORRECT', tabs: ['Q', 'Shift', 'Swing'], bots: ['1/16', '0', '50%'] },
      hear: '—',
    },
    {
      ch: 2,
      say: '<b>敲 pad 選要處理哪幾顆</b>，或按 <b>B2</b> 一次全選。',
      targets: ['p2', 'p3'],
      screen: { t1: 'TIME CORRECT  2 PADS' },
      hear: '—',
    },
    {
      ch: 2,
      say: '轉 <b>K3</b> 調 <b>Swing</b>。音會往三連音的方向偏，拍子開始搖擺。',
      targets: ['k3'],
      screen: { t1: 'SWING   56%', tabs: ['Q', 'Shift', 'Swing'], bots: ['1/16', '0', '56%'] },
      hear: '節奏變得有搖擺感',
    },
    {
      ch: 2,
      say: '轉 <b>K2</b> 調 <b>Shift</b>，把選中的音整體往前或往後挪一點點。',
      targets: ['k2'],
      screen: { t1: 'SHIFT   +2', tabs: ['Q', 'Shift', 'Swing'], bots: ['1/16', '+2', '56%'] },
      hear: '整組音一起偏移',
    },
    {
      ch: 2,
      say: '按 <b>B3</b> 套用。不喜歡就<b>按住 SHIFT 再按 −</b> 復原。',
      targets: ['b3'],
      screen: { t1: 'DO IT!' },
      hear: '套用後的節奏',
      note: {
        kind: 'warn',
        title: 'Q 與 Swing 是全域的',
        body: '在這裡改了量化與 Swing，別的地方也會跟著變。Sequence Mode 與 Note Repeat 都會受影響。',
      },
    },
    {
      ch: 3,
      say: '推桿平常也有用。<b>按住 SHIFT 再按 PAD 9</b> 打開 Fader 選單。',
      targets: ['p9'],
      shift: true,
      screen: { t1: 'FADER MENU' },
      hear: '—',
    },
    {
      ch: 3,
      say: '轉 <b>ENCODER</b> 選推桿要控制什麼：音量、聲相、音高、濾波都可以。',
      targets: ['enc'],
      screen: { t1: 'FADER   PAD FILTER' },
      hear: '推桿推動時音色改變',
      note: {
        kind: 'win',
        title: '第 7 課完成',
        body: '推桿跟 K 旋鈕一樣是絕對位置，也需要接手。燈的亮度就是目前的值。',
      },
    },
  ],
};
