import type { Lesson } from '@/types/lesson';

export const s3_03: Lesson = {
  id: 's3-03',
  slug: 'pad-budget-planning',
  season: 3,
  index: 3,
  title: 'Pad 預算規劃',
  outcome: '一張動手前就寫好的 pad 分配表',
  minutes: 15,
  chapters: ['為什麼要先規劃', '四個區塊的配額', '寫成表'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s3-02'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：每專案 16 樣本乘以 8 個 Bank',
    '配額建議為本站整理，不是官方數字',
  ],
  checkpoints: [
    '你在動手之前先寫下了 pad 分配',
    '四個區塊的數量加起來沒有超過 16',
    '你留了至少兩顆 pad 給 resample 產物',
  ],
  steps: [
    {
      ch: 0,
      say: '上一課學會 resample 之後，最容易犯的錯是<b>邊做邊亂放</b>。',
      targets: ['pads'],
      screen: { t1: 'A01 Kick 02' },
      hear: '—',
    },
    {
      ch: 0,
      say: '收到一半才發現沒空 pad，就得回頭重做。<b>先規劃比較快</b>。',
      targets: ['p11'],
      shift: true,
      screen: { t1: 'RESAMPLE' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '規劃只要三分鐘',
        body: '拿張紙寫下哪一顆放什麼。這三分鐘會省下你一小時。',
      },
    },
    {
      ch: 1,
      say: '<b>鼓佔 6 到 10 顆</b>。大鼓、小鼓、兩種 hi-hat 是基本，其餘看曲風。',
      targets: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
      screen: { t1: 'DRUMS  6–10' },
      hear: '—',
    },
    {
      ch: 1,
      say: '<b>貝斯佔 3 到 5 顆</b>。如果用 16 Levels 彈音高，一顆就夠。',
      targets: ['p13', 'p14', 'p15'],
      screen: { t1: 'BASS  3–5' },
      hear: '—',
    },
    {
      ch: 1,
      say: '<b>旋律佔 3 到 5 顆</b>。和弦一個 pad 一個，四個和弦就四顆。',
      targets: ['p9', 'p10', 'p11', 'p12'],
      screen: { t1: 'MELODY  3–5' },
      hear: '—',
    },
    {
      ch: 1,
      say: '<b>氛圍佔 2 到 4 顆</b>。雜訊、環境音、過門音效都算在這裡。',
      targets: ['p7', 'p8'],
      screen: { t1: 'AMBIENCE  2–4' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '加起來會超過',
        body: '六加三加三加二已經十四。所以一定要靠 resample 把某些區塊收起來。',
      },
    },
    {
      ch: 2,
      say: '按 <b>PAD BANK</b> 想一下 Bank 怎麼分。<b>Bank A 放原始素材，Bank B 放 resample 產物</b>。',
      targets: ['bank'],
      screen: { t1: 'BANK A → B' },
      hear: '—',
    },
    {
      ch: 2,
      say: '這樣分的好處是：<b>要改就回 Bank A，要用就在 Bank B</b>。不會搞混。',
      targets: ['bank'],
      screen: { t1: 'BANK B' },
      hear: '—',
      note: {
        kind: 'tip',
        title: 'Pad Link 有個限制',
        body: 'Pad Link 只能連同一個 Bank 裡的 pad。要用它就別把兩個聲音分到不同 Bank。',
      },
    },
    {
      ch: 2,
      say: '最後一件事：<b>永遠留兩顆空的</b>。臨時想加東西時你會感謝自己。',
      targets: ['p15', 'p16'],
      screen: { t1: 'RESERVED' },
      hear: '—',
      note: {
        kind: 'win',
        title: '第 3 課完成',
        body: '規劃是這台機器上最被低估的技巧。下一課讓貝斯只佔一顆 pad。',
      },
    },
  ],
};
