import type { Lesson } from '@/types/lesson';

export const s3_04: Lesson = {
  id: 's3-04',
  slug: 'play-bass-with-16-levels',
  season: 3,
  index: 4,
  title: '用 16 Levels 彈貝斯與旋律',
  outcome: '一段用單一樣本彈出來的貝斯線',
  minutes: 25,
  chapters: ['一顆聲音變十六個音', '找到你的音', '彈成一段', '換成濾波型式'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s3-03'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：16 Levels 的 Tune 型式原始音高在 PAD 4；Filter 型式 PAD 1–8 由最小值升到目前值，PAD 9–16 由目前值升到最大值',
    '操作流程為實機實測後自行撰寫',
  ],
  checkpoints: [
    '你用一顆樣本彈出了至少四個不同音高',
    '你知道原始音高在 PAD 4',
    '那段貝斯已經錄進序列裡',
    '你試過把型式換成 Filter',
  ],
  steps: [
    {
      ch: 0,
      say: '貝斯不用佔好幾顆 pad。<b>16 Levels</b> 可以把一個聲音變成十六個音高。',
      targets: ['lev16'],
      screen: { t1: '16 LEVELS' },
      hear: '—',
    },
    {
      ch: 0,
      say: '先敲你要當貝斯的那顆 <b>pad</b> 選中它。低音、尾巴長一點的比較好用。',
      targets: ['p13'],
      screen: { t1: 'A13 Bass 01', wave: 44 },
      hear: '一個低音',
    },
    {
      ch: 0,
      say: '按 <b>16 LEVELS</b>。現在十六顆 pad 全部變成同一個聲音的十六種變化。',
      targets: ['lev16'],
      screen: { t1: '16 LEVELS ON', tabs: ['Type', '', ''], bots: ['', '', ''] },
      hear: '—',
    },
    {
      ch: 0,
      say: '<b>按住 SHIFT 再按 16 LEVELS</b> 選 Type。把型式切到 <b>Tune</b>。',
      targets: ['lev16'],
      shift: true,
      screen: { t1: 'TYPE   TUNE', tabs: ['Type', '', ''], bots: ['Tune', '', ''] },
      hear: '—',
    },
    {
      ch: 1,
      say: '記住這件事：<b>原始音高在 PAD 4</b>。比它低的在左下，比它高的在右上。',
      targets: ['p4'],
      screen: { t1: 'TUNE   PAD 4 = 原音' },
      hear: '原本的音高',
      note: {
        kind: 'tip',
        title: '為什麼是 PAD 4',
        body: '這樣往下還有三顆可以壓低音。做貝斯常常需要比原音更低。',
      },
    },
    {
      ch: 1,
      say: '從 <b>PAD 4</b> 開始往兩邊敲。<b>先找到你要的根音</b>，其他音再從它出發。',
      targets: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8'],
      screen: { t1: 'TUNE' },
      hear: '同一個聲音的不同音高',
    },
    {
      ch: 1,
      say: '挑出<b>四個好聽的音</b>就夠了。貝斯線用的音其實很少。',
      targets: ['p2', 'p4', 'p6', 'p9'],
      screen: { t1: 'TUNE   4 NOTES' },
      hear: '四個音高',
    },
    {
      ch: 2,
      say: '按 <b>SEQ RECORD</b> 再按 <b>PLAY</b>。跟著鼓把那四個音彈成一小節。',
      targets: ['qrec', 'play'],
      screen: { t1: '● REC   BASS' },
      hear: '鼓加你彈的貝斯',
    },
    {
      ch: 2,
      say: '<b>彈得少一點</b>。貝斯留白比貝斯忙碌好聽，尤其在鼓很滿的時候。',
      targets: ['p2', 'p4', 'p6'],
      screen: { t1: '● REC   OVERDUB' },
      hear: '貝斯線逐漸成形',
      note: {
        kind: 'tip',
        title: '一個檢查方法',
        body: '把鼓關掉單獨聽貝斯。如果單獨聽像一段旋律，那就對了。',
      },
    },
    {
      ch: 3,
      say: '型式不只有 Tune。<b>按住 SHIFT 再按 16 LEVELS</b> 換成 <b>Filter</b> 試試看。',
      targets: ['lev16'],
      shift: true,
      screen: { t1: 'TYPE   FILTER', tabs: ['Type', '', ''], bots: ['Filter', '', ''] },
      hear: '—',
    },
    {
      ch: 3,
      say: 'Filter 型式下，<b>PAD 1 到 8 由最暗升到目前值</b>，<b>PAD 9 到 16 由目前值升到最亮</b>。',
      targets: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8'],
      screen: { t1: 'FILTER  16 STEPS' },
      hear: '同一個聲音，明亮度逐漸改變',
      note: {
        kind: 'win',
        title: '第 4 課完成',
        body: '一顆樣本現在能當旋律樂器用。下一課學另一種不用 resample 的疊層法。',
      },
    },
  ],
};
