import type { Lesson } from '@/types/lesson';

export const s3_01: Lesson = {
  id: 's3-01',
  slug: 'single-kit-ceiling',
  season: 3,
  index: 1,
  title: '單 kit 的天花板',
  outcome: '一份你自己的破解策略清單',
  minutes: 15,
  chapters: ['先看見天花板', '四條出路', '怎麼選'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s1-01', 's1-04'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Resample、Pad Link、Load Kit、Song Mode',
    '策略取捨為本站整理',
  ],
  checkpoints: [
    '你說得出這台機器的核心限制是什麼',
    '你知道四條出路各自的代價',
    '你能替下一首歌選出要用哪一條',
  ],
  steps: [
    {
      ch: 0,
      say: '敲一敲 <b>16 顆 pad</b>。這就是你一次能用的全部聲音。',
      targets: ['pads'],
      screen: { t1: 'A01 Kick 02' },
      hear: '十六個聲音',
    },
    {
      ch: 0,
      say: '按 <b>PAD BANK</b> 可以換到別的 Bank。但你沒辦法在既有 kit 之外，再疊上第二組音色。',
      targets: ['bank'],
      screen: { t1: 'BANK B' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '這是設計，不是故障',
        body: '這台機器的定位是快速做出東西，不是無限堆疊。認清這件事，做法就會變。',
      },
    },
    {
      ch: 0,
      say: '天花板通常在<b>第三層</b>出現。鼓佔掉一半，貝斯再幾顆，旋律就沒地方放了。',
      targets: ['pads'],
      screen: { t1: 'PADS FULL' },
      hear: '—',
    },
    {
      ch: 1,
      say: '第一條出路，<b>Resample</b>。<b>按住 SHIFT 再按 PAD 11</b>，把整段序列收成一顆 pad。',
      targets: ['p11'],
      shift: true,
      screen: { t1: 'RESAMPLE SEQ' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '代價是什麼',
        body: '收起來之後就不能單獨修改裡面的聲音了。所以收之前要先確定滿意。',
      },
    },
    {
      ch: 1,
      say: '第二條，<b>Pad Link</b>。在 Play 頁<b>按住 SHIFT 再轉 K2</b>，讓一顆 pad 同時觸發另一顆。',
      targets: ['k2'],
      shift: true,
      screen: { t1: 'PAD LINK', tabs: ['Play', '', ''], bots: ['', 'Link', ''] },
      hear: '—',
      note: {
        kind: 'tip',
        title: '好處是可以反悔',
        body: '兩個聲音還是分開的，隨時可以解除連結。但只能在同一個 Bank 裡連。',
      },
    },
    {
      ch: 1,
      say: '第三條，<b>Load Kit</b>。在 Project 選 Kits 分類，按 <b>B3</b> 只換音色、不動編曲。',
      targets: ['p16'],
      shift: true,
      screen: { t1: 'LOAD KIT', tabs: ['Load', 'Save', 'New'] },
      hear: '—',
      note: {
        kind: 'tip',
        title: '按 ENCODER 跟按 B3 不一樣',
        body: '按 ENCODER 會連四個預設序列一起載入，你的編曲就沒了。要保留編曲請按 B3。',
      },
    },
    {
      ch: 1,
      say: '第四條，<b>Song Mode</b>。不同段落做成不同序列，再串起來。',
      targets: ['p12'],
      shift: true,
      screen: { t1: 'SONG' },
      hear: '—',
    },
    {
      ch: 2,
      say: '選法很簡單。<b>要疊層就 Resample</b>，只是想兩顆一起響就 Pad Link。',
      targets: ['p11', 'k2'],
      shift: true,
      screen: { t1: 'STRATEGY' },
      hear: '—',
    },
    {
      ch: 2,
      say: '<b>換音色不換編曲用 Load Kit</b>。段落不同就用 Song Mode 串。',
      targets: ['p16', 'p12'],
      shift: true,
      screen: { t1: 'STRATEGY' },
      hear: '—',
      note: {
        kind: 'win',
        title: '第 1 課完成',
        body: '限制不會消失，但你現在知道怎麼繞過去。下一課做全站最重要的那一招。',
      },
    },
  ],
};
