import type { Lesson } from '@/types/lesson';

export const s3_05: Lesson = {
  id: 's3-05',
  slug: 'pad-link-layering',
  season: 3,
  index: 5,
  title: 'Pad Link：免 resample 疊層',
  outcome: '一顆 pad 同時觸發兩個聲音的設定',
  minutes: 15,
  chapters: ['它跟 resample 差在哪', '怎麼設', '兩個限制'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s3-02'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Play 頁 SHIFT + K2 設定 Pad Link，數值 Off 或 1–16，限同一個 Pad Bank',
    '操作流程為實機實測後自行撰寫',
  ],
  checkpoints: [
    '你設好了一組 Pad Link 並聽到兩個聲音同時響',
    '你知道連結值要設在被觸發的那一顆上',
    '你知道 Pad Link 只能連同一個 Bank',
  ],
  steps: [
    {
      ch: 0,
      say: 'Resample 會把聲音<b>永久合併</b>。Pad Link 不會，兩個聲音還是分開的。',
      targets: ['p11'],
      shift: true,
      screen: { t1: 'RESAMPLE vs LINK' },
      hear: '—',
    },
    {
      ch: 0,
      say: '差別就是<b>能不能反悔</b>。想保留調整空間就用 Pad Link。',
      targets: ['k2'],
      shift: true,
      screen: { t1: 'PAD LINK' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '什麼時候用哪一個',
        body: 'Pad 快用完就 resample。只是想兩個聲音一起響，就用 Pad Link。',
      },
    },
    {
      ch: 1,
      say: '舉個例子。旋律在 <b>PAD 6</b>，鼓的循環在 <b>PAD 7</b>，你想敲 7 的時候 6 也響。',
      targets: ['p6', 'p7'],
      screen: { t1: 'A06 / A07' },
      hear: '兩個分開的聲音',
    },
    {
      ch: 1,
      say: '先敲 <b>PAD 7</b> 選中它。<b>設定要下在你會去敲的那一顆上</b>。',
      targets: ['p7'],
      screen: { t1: 'A07 Drum Break' },
      hear: '鼓的循環',
      note: {
        kind: 'warn',
        title: '方向很容易搞反',
        body: '你敲哪一顆，就在哪一顆上設。設錯方向會變成另一顆去觸發它。',
      },
    },
    {
      ch: 1,
      say: '在 Play 頁<b>按住 SHIFT 再轉 K2</b>，把 Pad Link 的值轉到 <b>6</b>。',
      targets: ['k2'],
      shift: true,
      screen: { t1: 'PAD LINK   6', tabs: ['Play', '', ''], bots: ['', 'Link 6', ''] },
      hear: '—',
    },
    {
      ch: 1,
      say: '現在敲 <b>PAD 7</b>。兩個聲音同時出來了。',
      targets: ['p7'],
      screen: { t1: 'A07 + A06' },
      hear: '鼓與旋律同時響',
    },
    {
      ch: 2,
      say: '限制一：<b>只能連同一個 Pad Bank</b>。跨 Bank 連不了。',
      targets: ['bank'],
      screen: { t1: 'SAME BANK ONLY' },
      hear: '—',
    },
    {
      ch: 2,
      say: '限制二：<b>它不會空出 pad</b>。兩顆還是佔兩顆，只是一起響。',
      targets: ['p6', 'p7'],
      screen: { t1: 'PAD LINK   6' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '這一點最常被誤會',
        body: 'Pad Link 解決的是演奏問題，不是 pad 不夠的問題。要空出 pad 還是得 resample。',
      },
    },
    {
      ch: 2,
      say: '不要了就<b>把值轉回 Off</b>。隨時可以解除，這是它最大的好處。',
      targets: ['k2'],
      shift: true,
      screen: { t1: 'PAD LINK   OFF' },
      hear: '只剩鼓的循環',
      note: {
        kind: 'win',
        title: '第 5 課完成',
        body: '現在你有兩種疊層法，一種永久一種可反悔。下一課做段落結構。',
      },
    },
  ],
};
