import type { Lesson } from '@/types/lesson';

export const s3_09: Lesson = {
  id: 's3-09',
  slug: 'song-mode-arrangement',
  season: 3,
  index: 9,
  title: 'Song Mode 串接',
  outcome: '一首從頭到尾播得完的歌',
  minutes: 25,
  chapters: ['先準備好段落', '插入與刪除', '聽整首'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s3-06'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：SHIFT + PAD 12 進 Song Mode，用 pad 選序列、B3 插入、B2 移除、ENCODER 或 −/＋ 瀏覽',
    '操作流程為實機實測後自行撰寫',
  ],
  checkpoints: [
    '你有至少三段不同的序列',
    '那些序列已經串成一首歌',
    '整首從頭播到尾沒有斷掉',
    '你知道 Song Mode 不能分軌處理',
  ],
  steps: [
    {
      ch: 0,
      say: 'Song Mode 是把<b>已經做好的序列排成順序</b>。它不會幫你做新東西。',
      targets: ['p12'],
      shift: true,
      screen: { t1: 'SONG' },
      hear: '—',
    },
    {
      ch: 0,
      say: '所以先把段落做齊。<b>至少要有主歌、副歌、過門</b>三段序列。',
      targets: ['seq'],
      screen: { t1: 'SEQ 01 / 02 / 03' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '最省事的做法',
        body: '副歌是主歌用 Double Seq 加東西做出來的。不必從零開始。',
      },
    },
    {
      ch: 1,
      say: '<b>按住 SHIFT 再按 PAD 12</b> 進 Song Mode。',
      targets: ['p12'],
      shift: true,
      screen: { t1: 'SONG  EMPTY', tabs: ['', 'Remove', 'Insert'] },
      hear: '—',
    },
    {
      ch: 1,
      say: '用 <b>pad</b> 選序列。<b>有內容的 pad 是亮的，空的是暗的</b>，一眼就看得出來。',
      targets: ['pads'],
      screen: { t1: 'SONG  SELECT SEQ' },
      hear: '—',
    },
    {
      ch: 1,
      say: '選好之後按 <b>B3</b> 插入。它會排在目前被選中的那一段後面。',
      targets: ['b3'],
      screen: { t1: 'SONG  1. SEQ 01', tabs: ['', 'Remove', 'Insert'] },
      hear: '—',
    },
    {
      ch: 1,
      say: '重複這個動作：<b>選 pad</b>，按 <b>B3</b>。把主歌、副歌、過門一段一段排進去。',
      targets: ['pads', 'b3'],
      screen: { t1: 'SONG  4 PARTS' },
      hear: '—',
    },
    {
      ch: 1,
      say: '轉 <b>ENCODER</b> 或按 <b>−/＋</b> 在清單裡移動，看目前選到哪一段。',
      targets: ['enc', 'minus', 'plus'],
      screen: { t1: 'SONG  3 / 4' },
      hear: '—',
    },
    {
      ch: 1,
      say: '排錯了就選中它再按 <b>B2</b> 移除。只移除清單裡的那一筆，序列本身不會消失。',
      targets: ['b2'],
      screen: { t1: 'SONG  3 PARTS' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '可以重複使用',
        body: '同一段序列可以插入很多次。主歌用兩次、副歌用三次，很正常。',
      },
    },
    {
      ch: 2,
      say: '按 <b>PLAY</b> 從頭播放整首。這是你第一次聽到完整的作品。',
      targets: ['play'],
      screen: { t1: 'SONG  ▶  1 / 4' },
      hear: '整首歌從頭到尾',
    },
    {
      ch: 2,
      say: '聽到不順的地方就<b>回去改那一段序列</b>，Song Mode 這邊會跟著更新。',
      targets: ['seq'],
      screen: { t1: 'SEQ 02' },
      hear: '—',
    },
    {
      ch: 2,
      say: '一件要先知道的事：<b>Song Mode 沒有分軌</b>。整首只能一起處理。',
      targets: ['p12'],
      shift: true,
      screen: { t1: 'SONG' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '這會影響你的做法',
        body: '想單獨調某個樂器，要在做序列的階段就調好。到了 Song Mode 就來不及了。',
      },
    },
    {
      ch: 2,
      say: '<b>按住 SHIFT 再按 PAD 16</b> 存檔。下一課把它變成可以拿出去的檔案。',
      targets: ['p16'],
      shift: true,
      screen: { t1: 'SAVE PROJECT' },
      hear: '—',
      note: {
        kind: 'win',
        title: '第 9 課完成',
        body: '你手上有一首完整的歌了。剩下最後一件事：把它拿出來。',
      },
    },
  ],
};
