import type { Lesson } from '@/types/lesson';

export const s3_06: Lesson = {
  id: 's3-06',
  slug: 'half-and-double-sequences',
  season: 3,
  index: 6,
  title: '段落結構：Half 與 Double',
  outcome: '同一段素材做出來的四種長度變化',
  minutes: 20,
  chapters: ['四顆 pad 的分工', '改長度', '改速度', '拿來做什麼'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s3-02'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：PAD 2 Half Seq 長度砍半、PAD 3 Double Seq 長度加倍並複製已錄事件、PAD 6 Half Speed 讓事件以半速播放',
    '操作流程為實機實測後自行撰寫',
  ],
  checkpoints: [
    '你能說出 Half Seq 與 Half Speed 的差別',
    '你用同一段素材做出了至少兩種長度',
    '你知道 Double Seq 會把已錄的音一起複製',
  ],
  steps: [
    {
      ch: 0,
      say: '四顆 pad 管段落結構。<b>按住 SHIFT</b> 看它們上面的紅字。',
      targets: ['p2', 'p3', 'p6', 'p7'],
      shift: true,
      screen: { t1: 'SEQ TOOLS' },
      hear: '—',
    },
    {
      ch: 0,
      say: '<b>PAD 2 和 PAD 3 改的是長度</b>。<b>PAD 6 和 PAD 7 改的是速度</b>。兩件不一樣的事。',
      targets: ['p2', 'p3', 'p6', 'p7'],
      shift: true,
      screen: { t1: 'LENGTH vs SPEED' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '這是最常混淆的一組',
        body: '長度變了，音符位置不變。速度變了，音符會擠在一起或散開。',
      },
    },
    {
      ch: 1,
      say: '先按 <b>PLAY</b> 聽一次你的兩小節循環，記住它現在的樣子。',
      targets: ['play'],
      screen: { t1: 'SEQ 01  ▶  2 bars' },
      hear: '兩小節循環',
    },
    {
      ch: 1,
      say: '<b>按住 SHIFT 再按 PAD 3</b>，也就是 DOUBLE SEQ。兩小節變成四小節。',
      targets: ['p3'],
      shift: true,
      screen: { t1: 'DOUBLE SEQ  →  4 bars' },
      hear: '同樣的東西，但循環變長了',
      note: {
        kind: 'tip',
        title: '它會複製已錄的音',
        body: '後面兩小節是前面兩小節的複製。這正好，你可以只改後半段。',
      },
    },
    {
      ch: 1,
      say: '進 <b>SEQ RECORD</b>，只在<b>後兩小節</b>加東西。這樣就有 A 段跟 A 段變化。',
      targets: ['qrec', 'play'],
      screen: { t1: '● REC   BAR 3/4' },
      hear: '後半段多了新的音',
    },
    {
      ch: 1,
      say: '<b>按住 SHIFT 再按 PAD 2</b> 是 HALF SEQ，長度砍回一半。',
      targets: ['p2'],
      shift: true,
      screen: { t1: 'HALF SEQ  →  2 bars' },
      hear: '循環變短，只剩前半段',
      note: {
        kind: 'warn',
        title: '砍掉的部分回不來',
        body: '砍半之前先存檔。後半段的音會直接消失。',
      },
    },
    {
      ch: 2,
      say: '<b>按住 SHIFT 再按 PAD 6</b> 是 HALF SPEED。所有音用一半速度播放。',
      targets: ['p6'],
      shift: true,
      screen: { t1: 'HALF SPEED' },
      hear: '整段慢下來，音符之間變寬',
    },
    {
      ch: 2,
      say: '原本八分音符的 hi-hat，現在變成四分音符。<b>音符數量沒變，間隔變寬了</b>。',
      targets: ['p6'],
      shift: true,
      screen: { t1: 'HALF SPEED' },
      hear: 'hi-hat 變得稀疏',
    },
    {
      ch: 2,
      say: '<b>按住 SHIFT 再按 PAD 7</b> 是 DOUBLE SPEED，反過來擠成一半。',
      targets: ['p7'],
      shift: true,
      screen: { t1: 'DOUBLE SPEED' },
      hear: '整段變得密集急促',
    },
    {
      ch: 3,
      say: '實際用法：<b>Double Seq 做主歌變副歌</b>，長度變長才有空間鋪陳。',
      targets: ['p3'],
      shift: true,
      screen: { t1: 'DOUBLE SEQ' },
      hear: '—',
    },
    {
      ch: 3,
      say: '<b>Double Speed 做過門</b>，最後兩拍擠一下再回到原速，緊張感立刻出來。',
      targets: ['p7'],
      shift: true,
      screen: { t1: 'DOUBLE SPEED' },
      hear: '急促的過門',
      note: {
        kind: 'win',
        title: '第 6 課完成',
        body: '同一段素材現在有四種面貌。下一課讓它聽起來像人彈的。',
      },
    },
  ],
};
