import type { Lesson } from '@/types/lesson';

export const s3_10: Lesson = {
  id: 's3-10',
  slug: 'export-backup-load-kit',
  season: 3,
  index: 10,
  title: '匯出、備份、換音色',
  outcome: '一個存在你自己電腦裡的作品音檔',
  minutes: 25,
  chapters: ['匯出成音檔', '傳到電腦', '換音色不換編曲'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s3-09'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Song 頁 B1 匯出、B2 音訊混音或新序列、ENCODER 命名、B3 Do It!；Project 選單 SD Card Access 掛載 microSD；Kits 分類按 B3 只載入 kit 樣本',
    '操作流程為實機實測後自行撰寫',
  ],
  checkpoints: [
    '你的歌已經匯出成一個音檔',
    '那個音檔已經傳到電腦或備份出去',
    '你試過用 Load Kit 換音色而編曲沒有跑掉',
  ],
  steps: [
    {
      ch: 0,
      say: '在 Song 頁按 <b>B1</b> 開始匯出。這是把作品拿出來的唯一入口。',
      targets: ['b1'],
      screen: { t1: 'SONG  EXPORT', tabs: ['Export', '', ''] },
      hear: '—',
    },
    {
      ch: 0,
      say: '有兩個選擇。按 <b>B2</b> 匯出成<b>音檔</b>，這是你要的。',
      targets: ['b2'],
      screen: { t1: 'AUDIO MIXDOWN', tabs: ['Cancel', 'Audio', 'Do It!'] },
      hear: '—',
      note: {
        kind: 'tip',
        title: '另一個選擇是轉成新序列',
        body: '整首變成一段序列，可以再拿去疊層或加效果。不是拿出去用的。',
      },
    },
    {
      ch: 0,
      say: '轉 <b>ENCODER</b> 選字，按下去確認並跳到下一個字。取個以後找得到的名字。',
      targets: ['enc'],
      screen: { t1: 'NAME  MY_SONG_01' },
      hear: '—',
    },
    {
      ch: 0,
      say: '要打大寫就<b>按住 SHIFT</b>。打錯按 <b>B2</b> 刪一個字，<b>SHIFT 加 B2</b> 全部刪掉。',
      targets: ['b2'],
      shift: true,
      screen: { t1: 'NAME  MY_SONG_01' },
      hear: '—',
    },
    {
      ch: 0,
      say: '名字打完按 <b>B3</b>，也就是 Do It!，開始匯出。',
      targets: ['b3'],
      screen: { t1: 'EXPORTING…' },
      hear: '—',
    },
    {
      ch: 1,
      say: '檔案匯出來了，但還在機器裡。<b>按住 SHIFT 再按 PAD 16</b> 進 Project。',
      targets: ['p16'],
      shift: true,
      screen: { t1: 'PROJECT', tabs: ['Load', 'Save', 'New'] },
      hear: '—',
    },
    {
      ch: 1,
      say: '選 <b>SD Card Access</b>，再用 USB-C 接電腦。記憶卡會變成電腦上的外接磁碟。',
      targets: ['r_usb'],
      screen: { t1: 'SD CARD ACCESS' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '記憶卡不含在盒裝內',
        body: '官方手冊寫得很清楚，microSD 要自己買。沒有卡就沒有這條路。',
      },
    },
    {
      ch: 1,
      say: '傳完檔案<b>先在電腦上安全退出磁碟</b>，再按 <b>B1</b> 離開這個模式。',
      targets: ['b1'],
      screen: { t1: 'SD CARD ACCESS' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '尚未驗證',
        body: '沒插記憶卡能不能取出作品，官方手冊兩處說法不一致。買一張卡最保險。',
      },
    },
    {
      ch: 2,
      say: '最後一招。編曲做好了但音色不喜歡？<b>不用重做</b>。',
      targets: ['p16'],
      shift: true,
      screen: { t1: 'PROJECT' },
      hear: '—',
    },
    {
      ch: 2,
      say: '進 Project 選 Load Project，切到 <b>Kits</b> 分類，挑一組你喜歡的。',
      targets: ['enc'],
      screen: { t1: 'LOAD  KITS' },
      hear: '—',
    },
    {
      ch: 2,
      say: '這裡是關鍵：<b>按 B3 的 Load Kit</b>，只換音色，你的序列全部保留。',
      targets: ['b3'],
      screen: { t1: 'LOAD KIT ONLY' },
      hear: '同樣的編曲，換了一組聲音',
      note: {
        kind: 'warn',
        title: '不要按 ENCODER',
        body: '按 ENCODER 會連四個預設序列一起載進來，你的編曲就沒了。認明 B3。',
      },
    },
    {
      ch: 2,
      say: '按 <b>PLAY</b> 聽聽看。同一段編曲，完全不同的氣氛。',
      targets: ['play'],
      screen: { t1: 'SONG  ▶  NEW KIT' },
      hear: '編曲不變，音色全換',
      note: {
        kind: 'win',
        title: '第 3 季完成',
        body: '你做完了一首歌，而且拿得出來。這台機器該證明的事，它已經證明了。',
      },
    },
  ],
};
