import type { Lesson } from '@/types/lesson';

export const s4_01: Lesson = {
  id: 's4-01',
  slug: 'four-effect-engines',
  season: 4,
  index: 1,
  title: '四套效果系統的分工',
  outcome: '一張你分得清楚的效果選擇表',
  minutes: 15,
  chapters: ['四個引擎', '最常搞反的一組', '怎麼選'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s1-02'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：四個效果引擎與 Effects Routes 為 Main Output、Input、Per-Pad',
    '操作流程為實機實測後自行撰寫',
  ],
  checkpoints: [
    '你說得出四個引擎各自套用在什麼範圍',
    '你知道能指定單一 pad 的是 Knob FX 不是 Pad FX',
    '你知道 Knob FX 一次只能開一個',
  ],
  steps: [
    {
      ch: 0,
      say: '這台機器有<b>四套效果系統</b>。搞清楚分工，比記住六十種效果重要得多。',
      targets: ['padfx', 'knobfx'],
      screen: { t1: 'FX ENGINES' },
      hear: '—',
    },
    {
      ch: 0,
      say: '第一套 <b>Pad FX</b>。用 pad 觸發，<b>按越用力效果越重</b>。',
      targets: ['padfx'],
      screen: { t1: 'PAD FX' },
      hear: '踩下去整段聲音改變',
    },
    {
      ch: 0,
      say: '第二套 <b>Flex Beat</b>。<b>按住 SHIFT 再按 PAD FX</b>，專門玩節奏切割。',
      targets: ['padfx'],
      shift: true,
      screen: { t1: 'FLEX BEAT' },
      hear: '—',
    },
    {
      ch: 0,
      say: '第三套 <b>Knob FX</b>。用 K1 到 K3 控制，一次一個效果。',
      targets: ['knobfx'],
      screen: { t1: 'KNOB FX' },
      hear: '—',
    },
    {
      ch: 0,
      say: '第四套是內建<b>壓縮器</b>。<b>按住 SHIFT 再按 PAD 5</b> 打開。',
      targets: ['p5'],
      shift: true,
      screen: { t1: 'COMPRESSOR' },
      hear: '—',
    },
    {
      ch: 1,
      say: '這裡是全站最重要的釐清。<b>Pad FX 套用在整段序列上</b>，不能只套一顆 pad。',
      targets: ['padfx'],
      screen: { t1: 'PAD FX  →  WHOLE SEQ' },
      hear: '整段都變了',
      note: {
        kind: 'warn',
        title: '網路上這一點常常寫反',
        body: '很多說明會寫成 Pad FX 可以針對單一 pad。那是錯的，剛好相反。',
      },
    },
    {
      ch: 1,
      say: '<b>能指定 pad 的是 Knob FX</b>。官方手冊寫得很明白：可以套在任意數量的 pad 上。',
      targets: ['knobfx'],
      screen: { t1: 'KNOB FX  →  PER PAD' },
      hear: '只有指定的 pad 改變',
    },
    {
      ch: 1,
      say: 'Flex Beat 跟 Pad FX 一樣<b>套整段序列</b>。這兩套都不能挑 pad。',
      targets: ['padfx'],
      shift: true,
      screen: { t1: 'FLEX BEAT  →  WHOLE SEQ' },
      hear: '—',
    },
    {
      ch: 2,
      say: '選擇很簡單。<b>想讓某一顆 pad 不一樣，只有 Knob FX 做得到</b>。',
      targets: ['knobfx'],
      screen: { t1: 'KNOB FX' },
      hear: '—',
    },
    {
      ch: 2,
      say: '<b>想在演出時即時丟效果，用 Pad FX</b>，因為手指按下去就有反應。',
      targets: ['padfx'],
      screen: { t1: 'PAD FX' },
      hear: '—',
      note: {
        kind: 'win',
        title: '第 1 課完成',
        body: 'Pad FX 同時最多四個，Knob FX 一次只能一個。這兩個上限決定了你的策略。',
      },
    },
  ],
};
