import type { Lesson } from '@/types/lesson';

export const s4_04: Lesson = {
  id: 's4-04',
  slug: 'knob-fx-tour',
  season: 4,
  index: 4,
  title: 'Knob FX 28 種導覽',
  outcome: '一份你自己的常用效果短名單',
  minutes: 25,
  chapters: ['怎麼選效果', '七大類走一遍', '一次一個的取捨'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s4-01'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Knob FX 共 28 種，K1–K3 與 SHIFT+K1–K3 各三個參數，可套用在任意數量的 pad 上',
    '分類方式為本站整理，官方手冊未分類',
  ],
  checkpoints: [
    '你知道怎麼切換 Knob FX 的效果',
    '你試過至少一種延遲、一種濾波、一種動態',
    '你選出了三個自己最常用的',
    '你知道 Knob FX 一次只能開一個',
  ],
  steps: [
    {
      ch: 0,
      say: '按 <b>KNOB FX</b>（橘色）。按鍵會亮起，目前用的效果會顯示在螢幕上。',
      targets: ['knobfx'],
      screen: { t1: 'KNOB FX   DELAY', bots: ['Time', 'Fdbk', 'Mix'] },
      hear: '—',
    },
    {
      ch: 0,
      say: '<b>按住 SHIFT 再按 KNOB FX</b> 是 FX SELECT，用來換效果。',
      targets: ['knobfx'],
      shift: true,
      screen: { t1: 'FX SELECT' },
      hear: '—',
    },
    {
      ch: 0,
      say: '螢幕下排會顯示 <b>K1 到 K3</b> 現在管什麼。看到 Shift 標示就代表<b>還有三個參數</b>。',
      targets: ['k1', 'k2', 'k3'],
      screen: { t1: 'KNOB FX   DELAY', bots: ['Time', 'Fdbk', 'Mix'] },
      hear: '—',
      note: {
        kind: 'tip',
        title: '每個效果有六個參數',
        body: 'K1 到 K3 三個，按住 SHIFT 再轉又是三個。完整清單在效果字典頁。',
      },
    },
    {
      ch: 1,
      say: '第一類<b>延遲</b>四種。Delay 最通用，<b>Tape Delay</b> 有老盤帶的抖動味。',
      targets: ['k1'],
      screen: { t1: 'TAPE DELAY', bots: ['Time', 'Fdbk', 'Mix'] },
      hear: '帶著抖動的回聲',
    },
    {
      ch: 1,
      say: '第二類<b>濾波</b>三種。HP、LP、BP 各一。<b>轉 K1 掃頻率</b>就是最常見的段落手法。',
      targets: ['k1'],
      screen: { t1: 'LP FILTER', bots: ['Freq', 'Reso', ''] },
      hear: '高頻被慢慢砍掉',
    },
    {
      ch: 1,
      say: '第三類<b>調變</b>四種。Phaser、Flanger、Ensemble、Multi-Chorus。它們讓聲音變厚也變動。',
      targets: ['k1'],
      screen: { t1: 'MULTI-CHORUS', bots: ['Rate', 'Depth', 'Mix'] },
      hear: '聲音變厚、開始晃動',
    },
    {
      ch: 1,
      say: '第四類<b>空間</b>。三種 Reverb 大中小，加上 Spring Reverb 與 Auto-Pan。',
      targets: ['k1'],
      screen: { t1: 'REVERB LARGE', bots: ['Pre-Dly', '', ''] },
      hear: '聲音退到很大的空間裡',
    },
    {
      ch: 1,
      say: '第五類<b>復古</b>三種，第六類<b>破壞</b>三種。這兩類下一課專門講。',
      targets: ['k1'],
      screen: { t1: 'VINTAGE EMULATOR' },
      hear: '聲音變舊、變髒',
    },
    {
      ch: 1,
      say: '第七類<b>動態</b>五種。Transient、Noise Gate、Bus Compressor。還有 Limiter 與 Pumper。',
      targets: ['k1'],
      screen: { t1: 'PUMPER', bots: ['Speed', '', ''] },
      hear: '整體開始規律地起伏',
    },
    {
      ch: 2,
      say: '重點來了。<b>Knob FX 一次只能開一個</b>。想要兩個效果就得取捨。',
      targets: ['knobfx'],
      screen: { t1: 'KNOB FX   1 ONLY' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '這個限制會逼你做決定',
        body: '想同時要延遲跟殘響？先套一個，resample 收起來，再套第二個。',
      },
    },
    {
      ch: 2,
      say: '<b>Knob FX 開著的時候，K1 到 K3 就被它佔用了</b>。要調別的參數要先退出。',
      targets: ['k1', 'k2', 'k3'],
      screen: { t1: 'KNOB FX   ACTIVE' },
      hear: '—',
      note: {
        kind: 'win',
        title: '第 4 課完成',
        body: '二十八種你不會全用。挑三個練熟，比三十個都會一點有用。',
      },
    },
  ],
};
