import type { Lesson } from '@/types/lesson';

export const s4_05: Lesson = {
  id: 's4-05',
  slug: 'dynamics-toolkit',
  season: 4,
  index: 5,
  title: '動態四件組',
  outcome: '一段音量平均、有推力的循環',
  minutes: 25,
  chapters: ['內建壓縮器', 'Bus Compressor 與 Limiter', 'Pumper 代替側鏈'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s4-04'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：SHIFT + PAD 5 開啟壓縮器頁、B1 為 Color、B3 為 Bypass、K1 為 Attack；Knob FX 的 Bus Compressor、Limiter、Pumper 參數',
    '操作流程為實機實測後自行撰寫',
  ],
  checkpoints: [
    '你聽得出壓縮前後的差別',
    '你試過 Color 開跟關',
    '你用 Limiter 讓整體音量拉齊而不破音',
    '你知道這台沒有側鏈，要用 Pumper 代替',
  ],
  steps: [
    {
      ch: 0,
      say: '先講白話。<b>壓縮器就是讓大聲的地方小聲一點</b>，整體聽起來比較平均。',
      targets: ['p5'],
      shift: true,
      screen: { t1: 'COMPRESSOR' },
      hear: '—',
    },
    {
      ch: 0,
      say: '<b>按住 SHIFT 再按 PAD 5</b> 打開壓縮器頁。這是機器內建的，不算在 Knob FX 裡。',
      targets: ['p5'],
      shift: true,
      screen: { t1: 'COMPRESSOR', tabs: ['Color', '', 'Bypass'], bots: ['Attack', '', ''] },
      hear: '—',
    },
    {
      ch: 0,
      say: '按 <b>B3</b> 可以 <b>Bypass</b>，也就是暫時關掉。開開關關，聽差別最快。',
      targets: ['b3'],
      screen: { t1: 'BYPASS   ON' },
      hear: '開的時候比較黏、比較平均',
    },
    {
      ch: 0,
      say: '轉 <b>K1</b> 調 <b>Attack</b>。<b>Attack 慢一點，鼓的衝擊才留得住</b>。',
      targets: ['k1'],
      screen: { t1: 'ATTACK', bots: ['Attack', '', ''] },
      hear: '鼓的頭變硬或變軟',
      note: {
        kind: 'tip',
        title: '一個常見錯誤',
        body: 'Attack 設太快會把鼓的衝擊壓掉，整段就變得軟綿綿。',
      },
    },
    {
      ch: 0,
      say: '按 <b>B1</b> 打開 <b>Color</b>。它會加一點低頻、一點音高不穩與飽和。',
      targets: ['b1'],
      screen: { t1: 'COLOR   ON', tabs: ['Color', '', 'Bypass'] },
      hear: '低頻變厚，帶一點盤帶的溫暖',
      note: {
        kind: 'tip',
        title: 'Color 不是萬用',
        body: '它加的是味道，不是修正。乾淨的曲風關掉比較好。',
      },
    },
    {
      ch: 1,
      say: '第二件是 Knob FX 裡的 <b>Bus Compressor</b>。它比較透明，適合整體處理。',
      targets: ['knobfx'],
      screen: { t1: 'BUS COMPRESSOR', bots: ['Attack', '', ''] },
      hear: '整體變得更黏、更有推力',
    },
    {
      ch: 1,
      say: '第三件是 <b>Limiter</b>。它把尖峰壓在天花板下，同時把整體推大聲。',
      targets: ['knobfx'],
      screen: { t1: 'LIMITER', bots: ['Gain', 'Ceiling', 'Release'] },
      hear: '整體變大聲但沒有破音',
    },
    {
      ch: 1,
      say: '轉 <b>K2</b> 設 <b>Ceiling</b>，那是音量的天花板。轉 <b>K1</b> 的 Gain 往上推。',
      targets: ['k1', 'k2'],
      screen: { t1: 'CEILING  -1.0 dB', bots: ['Gain', 'Ceiling', 'Release'] },
      hear: '音量變大，尖峰被壓住',
      note: {
        kind: 'warn',
        title: '推過頭會扁掉',
        body: 'Gain 一直加，動態就消失了。聽起來大聲，但沒有力氣。',
      },
    },
    {
      ch: 2,
      say: '第四件是 <b>Pumper</b>。<b>這台機器沒有側鏈</b>，它就是替代方案。',
      targets: ['knobfx'],
      screen: { t1: 'PUMPER', bots: ['Speed', '', ''] },
      hear: '整體隨著節奏規律起伏',
      note: {
        kind: 'tip',
        title: '側鏈是什麼',
        body: '就是大鼓一響，其他聲音自動變小聲一下。舞曲的呼吸感從這裡來。',
      },
    },
    {
      ch: 2,
      say: '轉 <b>K1</b> 把 <b>Speed 對到 1/4</b>，讓起伏跟著大鼓的拍子走。',
      targets: ['k1'],
      screen: { t1: 'SPEED   1/4', bots: ['Speed', '', ''] },
      hear: '每一拍都有一次吸吐',
      note: {
        kind: 'win',
        title: '第 5 課完成',
        body: '順序建議：先壓縮器、再 Bus Compressor、最後 Limiter。Pumper 看曲風加。',
      },
    },
  ],
};
