import type { Lesson } from '@/types/lesson';

export const s4_06: Lesson = {
  id: 's4-06',
  slug: 'vintage-emulation',
  season: 4,
  index: 6,
  title: '復古模擬',
  outcome: '同一段素材的五種年代感',
  minutes: 20,
  chapters: ['四台經典取樣機', '黑膠與卡帶', '疊起來會太髒'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s4-04'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Vintage Emulator 的 K1 Type 為 MPC3000、MPC60、SP1200、SP1200Ring；Vinyl Emulator 的 Tone／Crackle／Pitch；Tape Emulator 的 Wow／Noise／Pitch',
    '音色描述為本站實聽整理',
  ],
  checkpoints: [
    '你聽過四種 Vintage Emulator 的差別',
    '你用 Vinyl Emulator 加過雜訊',
    '你知道復古效果疊太多會糊掉',
  ],
  steps: [
    {
      ch: 0,
      say: '按 <b>KNOB FX</b>，<b>按住 SHIFT 再按一次</b>選到 <b>Vintage Emulator</b>。',
      targets: ['knobfx'],
      shift: true,
      screen: { t1: 'VINTAGE EMULATOR', bots: ['Type', '', ''] },
      hear: '—',
    },
    {
      ch: 0,
      say: '轉 <b>K1</b> 換 Type。四個選項是 <b>MPC3000</b>、<b>MPC60</b>、<b>SP1200</b>、SP1200Ring。',
      targets: ['k1'],
      screen: { t1: 'TYPE   MPC3000', bots: ['Type', '', ''] },
      hear: '同一段素材，四種不同的粗糙感',
    },
    {
      ch: 0,
      say: '<b>MPC60 最粗</b>，年代最早。<b>MPC3000 稍微乾淨一點</b>，是很多經典嘻哈的聲音。',
      targets: ['k1'],
      screen: { t1: 'TYPE   MPC60' },
      hear: '低位元的顆粒感',
    },
    {
      ch: 0,
      say: '<b>SP1200 的味道最特別</b>，高頻有獨特的沙沙感。做 boom bap 很多人指定要它。',
      targets: ['k1'],
      screen: { t1: 'TYPE   SP1200' },
      hear: '高頻帶著沙沙的質地',
    },
    {
      ch: 1,
      say: '換到 <b>Vinyl Emulator</b>。<b>K2 的 Crackle</b> 就是黑膠的雜訊量。',
      targets: ['k2'],
      screen: { t1: 'VINYL EMULATOR', bots: ['Tone', 'Crackle', 'Pitch'] },
      hear: '背景多了黑膠的劈啪聲',
    },
    {
      ch: 1,
      say: '<b>Crackle 開到聽得見但不吵</b>就好。開太大會蓋掉音樂本身。',
      targets: ['k2'],
      screen: { t1: 'CRACKLE   30%', bots: ['Tone', 'Crackle', 'Pitch'] },
      hear: '雜訊在背景，不搶戲',
    },
    {
      ch: 1,
      say: '換到 <b>Tape Emulator</b>。<b>K1 的 Wow</b> 讓音高微微飄，像老卡帶。',
      targets: ['k1'],
      screen: { t1: 'TAPE EMULATOR', bots: ['Wow', 'Noise', 'Pitch'] },
      hear: '音高輕微地飄動',
      note: {
        kind: 'tip',
        title: '為什麼不穩反而好聽',
        body: '完全準確的音高是數位才有的。一點點不穩，耳朵就會覺得是真的樂器。',
      },
    },
    {
      ch: 2,
      say: '這裡要克制。<b>Knob FX 一次只能開一個</b>，想疊就得 resample。',
      targets: ['p11'],
      shift: true,
      screen: { t1: 'RESAMPLE' },
      hear: '—',
    },
    {
      ch: 2,
      say: '但<b>疊兩層復古通常會糊掉</b>。選一個做到位，比疊三個都半調子好。',
      targets: ['knobfx'],
      screen: { t1: 'ONE IS ENOUGH' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '一個實用判斷',
        body: '加了效果之後如果聽不清楚小鼓在哪，就是太多了。退回去一點。',
      },
    },
    {
      ch: 2,
      say: '搭配建議：<b>Vintage Emulator 給鼓</b>，<b>Vinyl Emulator 鋪整體</b>。',
      targets: ['knobfx'],
      screen: { t1: 'VINTAGE + VINYL' },
      hear: '鼓有顆粒，整體有年代感',
      note: {
        kind: 'win',
        title: '第 6 課完成',
        body: '復古效果是最容易上癮的一類。做完隔天再聽一次，通常會想調淡一點。',
      },
    },
  ],
};
