import type { Lesson } from '@/types/lesson';

export const s4_03: Lesson = {
  id: 's4-03',
  slug: 'flex-beat',
  season: 4,
  index: 3,
  title: 'Flex Beat 節奏切割',
  outcome: '一段用 Flex Beat 做出來的即興變奏',
  minutes: 20,
  chapters: ['先認識 PAD 1', 'One Shot 與 Loop', 'Quantize 與混合量'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s4-01'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：SHIFT + PAD FX 進入、PAD 1 為 EMPTY、效果在 PAD 2–16、B3 切換 Quantize、K1 為 One Shot 或 Loop、K3 為乾濕 Mix',
    '操作流程為實機實測後自行撰寫',
  ],
  checkpoints: [
    '你知道 PAD 1 是 EMPTY 不做事',
    '你試過 One Shot 與 Loop 兩種模式',
    '你用 Quantize 讓效果對齊拍點',
    '你調過乾濕比例並聽出差別',
  ],
  steps: [
    {
      ch: 0,
      say: '按 <b>PLAY</b> 讓序列跑起來。Flex Beat 跟 Pad FX 一樣<b>套用在整段序列上</b>。',
      targets: ['play'],
      screen: { t1: 'SEQ 01  ▶' },
      hear: '你的循環',
    },
    {
      ch: 0,
      say: '<b>按住 SHIFT 再按 PAD FX</b> 進入 Flex Beat。面板紅字寫著 FLEX BEAT。',
      targets: ['padfx'],
      shift: true,
      screen: { t1: 'FLEX BEAT', tabs: ['Mode', '', 'Quantize'], bots: ['One Shot', '', 'Mix'] },
      hear: '—',
    },
    {
      ch: 0,
      say: '<b>PAD 1 是 EMPTY</b>，它什麼都不做。那是你的原點與逃生出口。',
      targets: ['p1'],
      screen: { t1: 'FLEX BEAT  EMPTY' },
      hear: '原本的循環，沒有變化',
      note: {
        kind: 'tip',
        title: '為什麼要有一個空的',
        body: '玩到一半想立刻回到原樣，敲 PAD 1 就好。演出時這一顆救命。',
      },
    },
    {
      ch: 0,
      say: '效果在 <b>PAD 2 到 PAD 16</b>。它們會扭曲音高、時間與音量。',
      targets: ['p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8'],
      screen: { t1: 'FLEX BEAT' },
      hear: '節奏被切碎、變速、跳動',
    },
    {
      ch: 1,
      say: '轉 <b>K1</b> 切換模式。<b>One Shot 是放完就自己回到 PAD 1</b>。',
      targets: ['k1'],
      screen: { t1: 'MODE   ONE SHOT', bots: ['One Shot', '', 'Mix'] },
      hear: '效果跑一次就恢復',
    },
    {
      ch: 1,
      say: '轉到 <b>Loop</b> 就會一直重複，直到你換一個效果或按回 PAD 1。',
      targets: ['k1'],
      screen: { t1: 'MODE   LOOP', bots: ['Loop', '', 'Mix'] },
      hear: '效果持續重複',
      note: {
        kind: 'tip',
        title: '什麼時候用哪一個',
        body: '過門用 One Shot，比較安全。想做一整段變奏才用 Loop。',
      },
    },
    {
      ch: 2,
      say: '按 <b>B3</b> 打開 <b>Quantize</b>。效果會從最近的拍點才開始生效。',
      targets: ['b3'],
      screen: { t1: 'QUANTIZE   ON', tabs: ['Mode', '', 'Quantize'] },
      hear: '效果切進來的時機變整齊',
      note: {
        kind: 'tip',
        title: '手不準就開它',
        body: '開了 Quantize，你早按晚按都會對到格子上。演出時幾乎一定要開。',
      },
    },
    {
      ch: 2,
      say: '轉 <b>K3</b> 調乾濕比例。<b>0% 只有原音，100% 完全聽不到原音</b>。',
      targets: ['k3'],
      screen: { t1: 'MIX   60%', bots: ['One Shot', '', '60%'] },
      hear: '效果與原音的比例改變',
    },
    {
      ch: 2,
      say: '實戰用法：<b>八小節的最後兩拍丟一次 One Shot</b>，然後回到 PAD 1。',
      targets: ['p5', 'p1'],
      screen: { t1: 'FLEX BEAT  →  EMPTY' },
      hear: '過門之後乾淨回到原本的循環',
      note: {
        kind: 'win',
        title: '第 3 課完成',
        body: 'Flex Beat 是最容易做出「這人會玩」印象的功能。但用多了就膩，克制一點。',
      },
    },
  ],
};
