import type { Lesson } from '@/types/lesson';

export const s4_07: Lesson = {
  id: 's4-07',
  slug: 'onboard-mastering-limits',
  season: 4,
  index: 7,
  title: '機上母帶能做到哪裡',
  outcome: '一首音量夠、但你知道極限在哪的成品',
  minutes: 20,
  chapters: ['先說做不到什麼', '做得到的三件事', '什麼時候該收手'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s4-05'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Knob FX 的 Limiter 與 Bus Compressor、Sample 頁的 Filter 功能、四個效果引擎清單',
    '取捨建議為本站整理，不是官方說法',
  ],
  checkpoints: [
    '你知道這台沒有專用的母帶等化器',
    '你用 Limiter 把整體音量拉齊過',
    '你知道自己這首歌是 demo 還是成品',
  ],
  steps: [
    {
      ch: 0,
      say: '先講做不到的。<b>這台沒有專用的母帶等化器</b>，不能細修頻段。',
      targets: ['knobfx'],
      screen: { t1: 'NO MASTER EQ' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '不要期待太多',
        body: '它是做東西的機器，不是修東西的機器。母帶要精細就得另外處理。',
      },
    },
    {
      ch: 0,
      say: '也<b>不能分軌</b>。Song Mode 只能整首一起處理，混完就定了。',
      targets: ['p12'],
      shift: true,
      screen: { t1: 'SONG  NO STEMS' },
      hear: '—',
    },
    {
      ch: 0,
      say: '還有一點：<b>沒有 plugin，也不能擴充</b>。你手上的效果就是全部。',
      targets: ['knobfx', 'padfx'],
      screen: { t1: 'NO PLUGINS' },
      hear: '—',
    },
    {
      ch: 1,
      say: '做得到的第一件：<b>用 Limiter 把整體音量拉齊</b>。這是最有效的一步。',
      targets: ['knobfx'],
      screen: { t1: 'LIMITER', bots: ['Gain', 'Ceiling', 'Release'] },
      hear: '整體變大聲且不破音',
    },
    {
      ch: 1,
      say: '<b>Ceiling 留一點空間</b>，不要頂到最上面。轉檔的時候會多出一點點。',
      targets: ['k2'],
      screen: { t1: 'CEILING  -1.0 dB' },
      hear: '—',
    },
    {
      ch: 1,
      say: '第二件：<b>用 Bus Compressor 把整體黏起來</b>。讓各層聽起來像同一首歌。',
      targets: ['knobfx'],
      screen: { t1: 'BUS COMPRESSOR', bots: ['Attack', '', ''] },
      hear: '各層變得更整體',
    },
    {
      ch: 1,
      say: '第三件：<b>用濾波做粗調</b>。低頻太多就用 HP Filter 砍一點。',
      targets: ['knobfx'],
      screen: { t1: 'HP FILTER', bots: ['Freq', 'Reso', ''] },
      hear: '低頻變乾淨',
      note: {
        kind: 'tip',
        title: '這是粗調不是精修',
        body: '濾波只能整段砍。要只修某一個樂器的頻段，這台做不到。',
      },
    },
    {
      ch: 2,
      say: '判斷標準很簡單。<b>用手機喇叭聽一次</b>，聽得清楚就夠了。',
      targets: ['vol'],
      screen: { t1: 'CHECK ON PHONE' },
      hear: '在小喇叭上的樣子',
    },
    {
      ch: 2,
      say: '<b>自己聽不會累就收手</b>。在這台上追求完美，投報率很低。',
      targets: ['play'],
      screen: { t1: 'GOOD ENOUGH' },
      hear: '你的成品',
      note: {
        kind: 'warn',
        title: '一個誠實的建議',
        body: '要正式發行，把匯出的音檔交給會做母帶的人。機上做到八分就好。',
      },
    },
    {
      ch: 2,
      say: '做完就<b>匯出、備份、往下一首走</b>。做完的歌比完美的半成品有價值。',
      targets: ['p12'],
      shift: true,
      screen: { t1: 'SONG  EXPORT' },
      hear: '—',
      note: {
        kind: 'win',
        title: '第 4 季完成',
        body: '你現在會用四套效果系統，也知道它們的天花板在哪。下一季上台。',
      },
    },
  ],
};
