import type { Lesson } from '@/types/lesson';

export const s4_02: Lesson = {
  id: 's4-02',
  slug: 'pad-fx-in-practice',
  season: 4,
  index: 2,
  title: 'Pad FX 16 種實戰',
  outcome: '一段用手指即時做出效果變化的循環',
  minutes: 25,
  chapters: ['十六顆 pad 十六種效果', '力度就是控制量', '四個的上限', 'Latch 鎖住'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s4-01'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Pad FX 用 PADS 1–16 觸發、力道越大效果越重、同時最多四個、B1 為 Latch',
    '操作流程為實機實測後自行撰寫',
  ],
  videos: [
    {
      youtubeId: '6nM5ujdDkmY',
      title: 'Akai MPC Sample Part 9 - Resampling Pad FX!',
      channel: 'DnC Music',
      why: '示範把 Pad FX 的結果 resample 收起來。文字講不清楚的手感，看影片最快。',
      lang: 'en',
      reviewed: false,
    },
  ],
  checkpoints: [
    '你試過至少五種 Pad FX',
    '你感覺得出按壓力道會改變效果量',
    '你知道同時開超過四個會發生什麼事',
    '你用 Latch 鎖住過一個效果',
  ],
  steps: [
    {
      ch: 0,
      say: '先按 <b>PLAY</b> 讓序列跑起來。<b>Pad FX 要在播放中才聽得出來</b>。',
      targets: ['play'],
      screen: { t1: 'SEQ 01  ▶' },
      hear: '你的循環',
    },
    {
      ch: 0,
      say: '按 <b>PAD FX</b>（橘色）。現在十六顆 pad 各自是一種效果。',
      targets: ['padfx'],
      screen: { t1: 'PAD FX', tabs: ['Latch', '', ''], bots: ['', '', ''] },
      hear: '—',
    },
    {
      ch: 0,
      say: '從濾波開始最有感。<b>PAD 6 低通</b>、<b>PAD 7 高通</b>、<b>PAD 8 帶通</b>。',
      targets: ['p6', 'p7', 'p8'],
      screen: { t1: 'LP / HP / BP FILTER' },
      hear: '聲音被砍掉一段頻率',
    },
    {
      ch: 0,
      say: '<b>PAD 13 是 Beat Repeat</b>，把當下那一小段一直重複。過門最好用。',
      targets: ['p13'],
      screen: { t1: 'BEAT REPEAT' },
      hear: '同一小段不斷結巴重複',
    },
    {
      ch: 0,
      say: '<b>PAD 10 是 LoFi</b>，聲音立刻變粗。<b>PAD 16 是 Reverb</b>，聲音退到遠處。',
      targets: ['p10', 'p16'],
      screen: { t1: 'LOFI / REVERB' },
      hear: '一個變粗糙，一個變遙遠',
    },
    {
      ch: 1,
      say: '這裡是 Pad FX 的靈魂。<b>你按越用力，效果套得越重</b>。',
      targets: ['p6'],
      screen: { t1: 'LP FILTER' },
      hear: '輕按微微變化，重按整個悶掉',
      note: {
        kind: 'tip',
        title: '這就是為什麼它適合演出',
        body: '你的手指就是旋鈕。不用看螢幕，用力道控制就好。',
      },
    },
    {
      ch: 1,
      say: '轉 <b>K1</b> 到 <b>K3</b> 可以調目前這個效果的參數。每種效果的參數不一樣。',
      targets: ['k1', 'k2', 'k3'],
      screen: { t1: 'LP FILTER', bots: ['Freq', 'Reso', 'Mix'] },
      hear: '效果的個性改變',
    },
    {
      ch: 2,
      say: '<b>同時最多四個</b>。按第五個的時候，最早按的那個會被停掉。',
      targets: ['p6', 'p10', 'p13', 'p16'],
      screen: { t1: 'PAD FX  4 ACTIVE' },
      hear: '四種效果疊在一起',
      note: {
        kind: 'warn',
        title: '被停掉的會回來',
        body: '第五個以後的效果關掉之後，剛剛被停掉的那個會自己再啟用。',
      },
    },
    {
      ch: 3,
      say: '想讓效果一直開著，按 <b>B1</b> 就是 <b>Latch</b>，把它鎖在目前的量。',
      targets: ['b1'],
      screen: { t1: 'LATCH ON', tabs: ['Latch', '', ''] },
      hear: '手放開效果還在',
    },
    {
      ch: 3,
      say: '要解除就<b>選那顆 pad 再按一次 B1</b>。手指就空出來做別的事了。',
      targets: ['b1'],
      screen: { t1: 'LATCH OFF' },
      hear: '效果消失',
      note: {
        kind: 'win',
        title: '第 2 課完成',
        body: 'Latch 是演出的關鍵。鎖住一個濾波，另一隻手就能繼續敲 pad。',
      },
    },
  ],
};
