import type { Lesson } from '@/types/lesson';

export const s5_06: Lesson = {
  id: 's5-06',
  slug: 'sync-and-stage-checklist',
  season: 5,
  index: 6,
  title: '同步外部設備與上台檢查表',
  outcome: '一份帶上台就照著跑的檢查清單',
  minutes: 25,
  chapters: ['MIDI 二選一', '同步設定', '電力與備援', '上台檢查表'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s5-05'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：MIDI Config 的 MIDI Port 為 External 或 USB 二選一、MIDI Sync In/Out 為 Off／MIDI Clock／MTC、MIDI Thru 設定；背板 MIDI 為 1/8" TRS Type A；電源可由 USB-C 匯流排、變壓器或行動電源（5V 2A，另購）供電；電池約 5 小時連續播放',
    '檢查表為本站整理',
  ],
  checkpoints: [
    '你知道 MIDI Port 只能選 External 或 USB 其中一個',
    '你設定過 MIDI Sync 的送或收',
    '你準備了行動電源或變壓器',
    '你照著檢查表跑過一次完整流程',
  ],
  steps: [
    {
      ch: 0,
      say: '<b>按住 SHIFT 再按 PAD 8</b> 打開 MIDI Config。所有同步設定都在這裡。',
      targets: ['p8'],
      shift: true,
      screen: { t1: 'MIDI CONFIG' },
      hear: '—',
    },
    {
      ch: 0,
      say: '第一個設定最重要。<b>MIDI Port 只能選 External 或 USB</b>，不能兩個一起。',
      targets: ['enc'],
      screen: { t1: 'MIDI PORT   EXTERNAL' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '二選一，沒有例外',
        body: 'External 走背板那兩個孔，USB 走 USB-C。接錯就是完全沒反應。',
      },
    },
    {
      ch: 0,
      say: '要接實體合成器或鼓機，選 <b>External</b>，用背板的 <b>MIDI IN</b> 與 <b>MIDI OUT</b>。',
      targets: ['r_midiin', 'r_midiout'],
      screen: { t1: 'MIDI PORT   EXTERNAL' },
      hear: '—',
    },
    {
      ch: 0,
      say: '背板那兩個是 <b>1/8 吋 TRS Type A</b>。<b>轉接線盒裝有附</b>，是 Type A 規格。',
      targets: ['r_midiout'],
      screen: { t1: 'TRS TYPE A' },
      hear: '—',
      note: {
        kind: 'warn',
        title: 'Type A 跟 Type B 不通用',
        body: '市面上兩種都有。買錯線接上去不會壞，但完全不會動。',
      },
    },
    {
      ch: 1,
      say: '往下捲到 <b>MIDI Sync Out</b>。<b>要當主控就設成 MIDI Clock</b>，讓別台跟你的速度。',
      targets: ['enc'],
      screen: { t1: 'SYNC OUT   MIDI CLOCK' },
      hear: '—',
    },
    {
      ch: 1,
      say: '<b>要跟別台就設 MIDI Sync In</b>。兩邊都設成送會打架，記得只有一台當主控。',
      targets: ['enc'],
      screen: { t1: 'SYNC IN   MIDI CLOCK' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '還有 SYNC OUT 孔',
        body: '背板另有一個 SYNC OUT，是 5V 的類比訊號，給老式設備用的。',
      },
    },
    {
      ch: 1,
      say: '背板的 <b>SYNC OUT</b> 跟 MIDI 是兩回事。它送的是電壓脈衝，不是 MIDI 訊息。',
      targets: ['r_sync'],
      screen: { t1: 'SYNC OUT   5V' },
      hear: '—',
    },
    {
      ch: 2,
      say: '電力。<b>電池約五小時連續播放</b>，但演出不要賭電池。',
      targets: ['r_usb'],
      screen: { t1: 'BATTERY  ~5 h' },
      hear: '—',
    },
    {
      ch: 2,
      say: '<b>帶一顆行動電源</b>。官方寫的規格是 5V 2A，而且要另外買。',
      targets: ['r_usb'],
      screen: { t1: 'POWER  5V 2A' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '線也要帶兩條',
        body: '有些 USB-C 線只能充電。帶一條確定能傳資料的，一條備用。',
      },
    },
    {
      ch: 3,
      say: '上台前一：<b>專案存過了嗎</b>。按住 SHIFT 再按 PAD 16 存一次。',
      targets: ['p16'],
      shift: true,
      screen: { t1: 'SAVE PROJECT' },
      hear: '—',
    },
    {
      ch: 3,
      say: '之二：<b>所有 pad 都解除靜音了嗎</b>。按住 SHIFT 再按 MUTE 全部打開。',
      targets: ['mute'],
      shift: true,
      screen: { t1: 'UNMUTE ALL' },
      hear: '所有聲音都在',
    },
    {
      ch: 3,
      say: '之三：<b>音量歸位</b>。MAIN VOLUME 先轉到一半，接上場地音響再慢慢加。',
      targets: ['vol'],
      screen: { t1: 'VOLUME  50%' },
      hear: '—',
    },
    {
      ch: 3,
      say: '之四：<b>Latch 有沒有忘記關</b>。上一場鎖住的效果會跟著你上台。',
      targets: ['padfx', 'b1'],
      screen: { t1: 'LATCH  OFF' },
      hear: '—',
    },
    {
      ch: 3,
      say: '之五：<b>快速連按兩下 STOP 練一次</b>。那是出事時你唯一要記得的動作。',
      targets: ['stop'],
      screen: { t1: 'ALL SOUND OFF' },
      hear: '瞬間安靜',
      note: {
        kind: 'win',
        title: '第 5 季完成',
        body: '三十四課走完了。你會錄音、切片、疊層、編曲、匯出，也會上台。剩下的是練習。',
      },
    },
  ],
};
