import type { Lesson } from '@/types/lesson';

export const s5_04: Lesson = {
  id: 's5-04',
  slug: 'finger-drumming-basics',
  season: 5,
  index: 4,
  title: 'Finger Drumming 基本功',
  outcome: '一套練得起來的四週練習表',
  minutes: 20,
  chapters: ['手指怎麼放', 'Note Repeat 是拐杖', '四週練習表'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s5-01'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：NOTE REPEAT 按一下啟用、長按為暫時啟用、用 B1–B3 選時值、啟用中按住 SHIFT 顯示三連音時值',
    '練習方法為本站整理',
  ],
  checkpoints: [
    '你有固定的手指位置，每次都一樣',
    '你能用 Note Repeat 打出穩定的 hi-hat',
    '你知道三連音時值怎麼叫出來',
    '你排出了自己的四週練習進度',
  ],
  steps: [
    {
      ch: 0,
      say: '先把位置固定。<b>大鼓放 PAD 1，小鼓放 PAD 2</b>，兩個食指負責。',
      targets: ['p1', 'p2'],
      screen: { t1: 'KICK / SNARE' },
      hear: '大鼓與小鼓',
    },
    {
      ch: 0,
      say: '<b>Hi-hat 放 PAD 3</b>，用中指。<b>Open hat 放 PAD 4</b>，用無名指。',
      targets: ['p3', 'p4'],
      screen: { t1: 'HATS' },
      hear: 'hi-hat 兩種',
    },
    {
      ch: 0,
      say: '<b>位置定了就不要再改</b>。肌肉記憶只有在位置固定時才長得出來。',
      targets: ['p1', 'p2', 'p3', 'p4'],
      screen: { t1: 'FIXED LAYOUT' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '一個常見錯誤',
        body: '每首歌換一套配置，練一年還是不熟。位置固定比配置好看重要。',
      },
    },
    {
      ch: 1,
      say: '按 <b>NOTE REPEAT</b>。按住 pad 就會依設定的時值自動連打。',
      targets: ['nrep'],
      screen: { t1: 'NOTE REPEAT', tabs: ['1/8', '1/16', '1/32'] },
      hear: '穩定的連續打擊',
    },
    {
      ch: 1,
      say: '用 <b>B1 到 B3</b> 選時值。八分、十六分、三十二分，越右邊越密。',
      targets: ['b1', 'b2', 'b3'],
      screen: { t1: 'DIVISION  1/16', tabs: ['1/8', '1/16', '1/32'] },
      hear: '連打的密度改變',
    },
    {
      ch: 1,
      say: '<b>連打啟用中按住 SHIFT</b>，B1 到 B3 會變成三連音時值。',
      targets: ['nrep'],
      shift: true,
      screen: { t1: 'TRIPLET', tabs: ['1/8T', '1/16T', '1/32T'] },
      hear: '三連音的連打',
    },
    {
      ch: 1,
      say: '也可以<b>長按 NOTE REPEAT 不放</b>當作暫時啟用，放開就恢復手打。',
      targets: ['nrep'],
      screen: { t1: 'NOTE REPEAT  TEMP' },
      hear: '按住時連打，放開恢復',
      note: {
        kind: 'warn',
        title: '它是拐杖不是腿',
        body: '連打很好用，但全程靠它會練不出手感。過門用它，主幹自己打。',
      },
    },
    {
      ch: 2,
      say: '<b>第一週</b>：只練大鼓與小鼓。跟著節拍器打四拍，每天十分鐘。',
      targets: ['p1', 'p2'],
      screen: { t1: 'WEEK 1' },
      hear: '大鼓小鼓交替',
    },
    {
      ch: 2,
      say: '<b>第二週</b>：加 hi-hat。三根手指同時動，速度放慢到你不會錯為止。',
      targets: ['p1', 'p2', 'p3'],
      screen: { t1: 'WEEK 2' },
      hear: '三件式的基本節奏',
    },
    {
      ch: 2,
      say: '<b>第三週</b>：練力度。同一顆 pad 打出明顯的大小聲差別。',
      targets: ['p3'],
      screen: { t1: 'WEEK 3  DYNAMICS' },
      hear: '同一個聲音，強弱分明',
    },
    {
      ch: 2,
      say: '<b>第四週</b>：加過門。每八小節做一次，用 NOTE REPEAT 或手打都行。',
      targets: ['p2', 'nrep'],
      screen: { t1: 'WEEK 4  FILLS' },
      hear: '八小節一次的過門',
      note: {
        kind: 'win',
        title: '第 4 課完成',
        body: '每天十分鐘，勝過週末練兩小時。這件事沒有捷徑。',
      },
    },
  ],
};
