import type { Lesson } from '@/types/lesson';

export const s5_05: Lesson = {
  id: 's5-05',
  slug: 'live-transitions',
  season: 5,
  index: 5,
  title: '轉場技巧',
  outcome: '三種不會失手的段落交接方式',
  minutes: 20,
  chapters: ['濾波推上去', 'Flex Beat 過門', '轉場序列'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s5-03', 's4-03'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Pad FX 的 Latch、Flex Beat 的 One Shot 與 Quantize、Knob FX 濾波參數',
    '轉場手法為本站整理',
  ],
  checkpoints: [
    '你能用濾波做出八小節的 build-up',
    '你用 Flex Beat 丟過一次乾淨的過門',
    '你準備了至少一段專用的轉場序列',
  ],
  steps: [
    {
      ch: 0,
      say: '轉場只有一個目的：<b>讓下一段進來的時候，聽起來是故意的</b>。',
      targets: ['play'],
      screen: { t1: 'SEQ 01  ▶' },
      hear: '目前的循環',
    },
    {
      ch: 0,
      say: '第一種最穩：<b>濾波推上去</b>。按 <b>KNOB FX</b> 選 <b>HP Filter</b>。',
      targets: ['knobfx'],
      screen: { t1: 'HP FILTER', bots: ['Freq', 'Reso', ''] },
      hear: '—',
    },
    {
      ch: 0,
      say: '在最後八小節<b>把 K1 慢慢往上轉</b>。低頻一點一點消失，張力就上來了。',
      targets: ['k1'],
      screen: { t1: 'FREQ  ↑', bots: ['Freq', 'Reso', ''] },
      hear: '低頻逐漸抽掉，聲音越來越薄',
    },
    {
      ch: 0,
      say: '換段的那一拍<b>把 K1 轉回去</b>。低頻整個回來，那一下最有效果。',
      targets: ['k1'],
      screen: { t1: 'FREQ  ↓' },
      hear: '低頻轟回來',
      note: {
        kind: 'tip',
        title: '為什麼這招不會失手',
        body: '它不需要準確的時機。你轉快轉慢都成立，只要方向對。',
      },
    },
    {
      ch: 1,
      say: '第二種：<b>Flex Beat 過門</b>。<b>按住 SHIFT 再按 PAD FX</b> 進去。',
      targets: ['padfx'],
      shift: true,
      screen: { t1: 'FLEX BEAT', tabs: ['Mode', '', 'Quantize'] },
      hear: '—',
    },
    {
      ch: 1,
      say: '<b>模式設 One Shot，Quantize 開啟</b>。這兩個設定讓你不容易搞砸。',
      targets: ['k1', 'b3'],
      screen: { t1: 'ONE SHOT + QUANTIZE', bots: ['One Shot', '', 'Mix'] },
      hear: '—',
    },
    {
      ch: 1,
      say: '最後兩拍<b>敲一顆效果 pad</b>，放完會自己回到 PAD 1。乾淨俐落。',
      targets: ['p5'],
      screen: { t1: 'FLEX BEAT  →  EMPTY' },
      hear: '兩拍的切碎效果，然後恢復',
      note: {
        kind: 'warn',
        title: '不要連續丟',
        body: '每段轉場只丟一次。丟太多會讓人覺得你在玩機器，不是在放音樂。',
      },
    },
    {
      ch: 2,
      say: '第三種最保險：<b>做一段專門的轉場序列</b>。事先做好，台上只要切過去。',
      targets: ['seq'],
      screen: { t1: 'SEQ 08  TRANSITION' },
      hear: '—',
    },
    {
      ch: 2,
      say: '轉場序列<b>做一到兩小節就好</b>。裡面放 crash、反轉音效、或只有鼓的段落。',
      targets: ['p2', 'p3'],
      screen: { t1: 'SEQ 08  1 bar' },
      hear: '短促的過門段落',
    },
    {
      ch: 2,
      say: '演出時就<b>切過去、跑一輪、再切到下一段</b>。手不忙，也不會出錯。',
      targets: ['p8', 'p2'],
      screen: { t1: 'SEQ 08 → SEQ 02' },
      hear: '過門之後接到新段落',
      note: {
        kind: 'win',
        title: '第 5 課完成',
        body: '三種轉場：濾波、Flex Beat、專用序列。緊張的時候用第三種最安全。',
      },
    },
  ],
};
