import type { Lesson } from '@/types/lesson';

export const s5_01: Lesson = {
  id: 's5-01',
  slug: 'performance-mindset',
  season: 5,
  index: 1,
  title: '表演思維',
  outcome: '一份你自己的演出素材準備清單',
  minutes: 15,
  chapters: ['製作與演出的差別', '準備什麼', '第一次上台的規模'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s3-08'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Sequence Mode、Mute、Pad Bank 操作',
    '演出建議為本站整理',
  ],
  checkpoints: [
    '你說得出製作與演出在心態上的差別',
    '你準備了至少四段可以互相接的序列',
    '你知道第一次上台不該做太多',
  ],
  steps: [
    {
      ch: 0,
      say: '製作的時候你在<b>做決定</b>。可以重來一百次，沒人在看。',
      targets: ['seq'],
      screen: { t1: 'SEQ 01' },
      hear: '—',
    },
    {
      ch: 0,
      say: '演出的時候你在<b>執行加即興</b>。不能重來，而且要一直有聲音。',
      targets: ['play'],
      screen: { t1: 'SEQ 01  ▶' },
      hear: '不能停的音樂',
      note: {
        kind: 'tip',
        title: '最重要的一條',
        body: '演出時最怕的不是彈錯，是突然沒聲音。留白要是你選的，不是意外。',
      },
    },
    {
      ch: 0,
      say: '所以準備方式完全不同。<b>製作求完美，演出求穩</b>。',
      targets: ['stop'],
      screen: { t1: 'SEQ 01  ■' },
      hear: '—',
    },
    {
      ch: 1,
      say: '準備第一件：<b>至少四段可以互相接的序列</b>。BPM 一樣，長度一樣。',
      targets: ['seq'],
      screen: { t1: 'SEQ 01–04' },
      hear: '—',
    },
    {
      ch: 1,
      say: '第二件：<b>每一段都先 resample 收乾淨</b>。上台不要臨時疊層。',
      targets: ['p11'],
      shift: true,
      screen: { t1: 'RESAMPLE' },
      hear: '—',
      note: {
        kind: 'warn',
        title: '為什麼要先收好',
        body: '疊層要好幾步，台上手會抖。收成一顆 pad，你只要敲一下。',
      },
    },
    {
      ch: 1,
      say: '第三件：<b>把 pad 位置固定下來</b>。哪一排放鼓、哪一排放旋律，每次都一樣。',
      targets: ['pads'],
      screen: { t1: 'FIXED LAYOUT' },
      hear: '—',
    },
    {
      ch: 1,
      say: '第四件：<b>存成一個專門的演出專案</b>，不要用製作用的那一個。',
      targets: ['p16'],
      shift: true,
      screen: { t1: 'SAVE  LIVE_SET_01' },
      hear: '—',
    },
    {
      ch: 2,
      say: '第一次上台<b>先做十分鐘就好</b>。四段序列，加上靜音與濾波就撐得住。',
      targets: ['mute'],
      screen: { t1: 'MUTE' },
      hear: '—',
    },
    {
      ch: 2,
      say: '<b>不要在第一場塞進所有會的東西</b>。少做一點但都做對，比較像回事。',
      targets: ['play'],
      screen: { t1: 'LIVE SET  ▶' },
      hear: '穩定的十分鐘',
      note: {
        kind: 'win',
        title: '第 1 課完成',
        body: '接下來五課給你四個工具：序列切換、靜音、手指打擊、轉場。夠了。',
      },
    },
  ],
};
