import type { Lesson } from '@/types/lesson';

export const s5_03: Lesson = {
  id: 's5-03',
  slug: 'live-muting',
  season: 5,
  index: 3,
  title: 'Mute 即興編排',
  outcome: '同一段循環現場變出來的四種編排',
  minutes: 20,
  chapters: ['紅色與黃色', '長按暫時用', '減法編曲'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s5-02'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：按 MUTE 啟用靜音功能，長按可暫時啟用、放開解除；靜音的 pad 亮紅，未靜音亮黃；SHIFT + MUTE 為 UNMUTE ALL',
    '編排手法為本站整理',
  ],
  checkpoints: [
    '你知道紅色與黃色分別代表什麼',
    '你用長按做過一次瞬間靜音',
    '你只靠靜音就從同一段做出三種編排',
    '你知道一鍵解除全部靜音的方法',
  ],
  steps: [
    {
      ch: 0,
      say: '先按 <b>PLAY</b> 讓循環跑起來。靜音要在播放中才有意義。',
      targets: ['play'],
      screen: { t1: 'SEQ 01  ▶' },
      hear: '完整的循環',
    },
    {
      ch: 0,
      say: '按 <b>MUTE</b>（藍色）。現在 pad 不發聲了，改成控制哪些聲音要不要響。',
      targets: ['mute'],
      screen: { t1: 'MUTE' },
      hear: '循環照常播放',
    },
    {
      ch: 0,
      say: '<b>敲一顆 pad 讓它變紅，那個聲音就消失</b>。再敲一次變回黃色就回來。',
      targets: ['p1'],
      screen: { t1: 'MUTE   PAD 01' },
      hear: '大鼓不見了',
      note: {
        kind: 'tip',
        title: '顏色就是狀態',
        body: '紅色是被靜音，黃色是正常。整片顏色一掃就知道現在是什麼編排。',
      },
    },
    {
      ch: 0,
      say: '這功能<b>在任何模式下都能用</b>。不必先切到什麼特別的畫面。',
      targets: ['mute'],
      screen: { t1: 'MUTE' },
      hear: '—',
    },
    {
      ch: 1,
      say: '真正好用的是<b>長按 MUTE 不放</b>。這樣是暫時啟用，放開就回到原本的模式。',
      targets: ['mute'],
      screen: { t1: 'MUTE  TEMP' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '演出時的用法',
        body: '左手長按 MUTE，右手拿掉一顆，放開左手就回去敲 pad。手不用離開機器。',
      },
    },
    {
      ch: 1,
      say: '玩壞了就<b>按住 SHIFT 再按 MUTE</b>，也就是 UNMUTE ALL，全部一次解除。',
      targets: ['mute'],
      shift: true,
      screen: { t1: 'UNMUTE ALL' },
      hear: '所有聲音回來',
      note: {
        kind: 'warn',
        title: '這是你的急救鍵',
        body: '台上搞混了不要慌，一鍵全開再重新拿掉。比一顆一顆找快。',
      },
    },
    {
      ch: 2,
      say: '減法編曲第一招：<b>只留鼓</b>。把旋律與貝斯全部靜音，段落立刻變成間奏。',
      targets: ['p9', 'p13'],
      screen: { t1: 'DRUMS ONLY' },
      hear: '只剩鼓在跑',
    },
    {
      ch: 2,
      say: '第二招：<b>只留旋律</b>。把鼓拿掉，剩下的旋律會突然變得很大。',
      targets: ['p1', 'p2', 'p3'],
      screen: { t1: 'MELODY ONLY' },
      hear: '鼓消失，旋律浮出來',
    },
    {
      ch: 2,
      say: '第三招：<b>一次拿掉一顆再一顆一顆放回來</b>。這是最簡單也最有效的 build-up。',
      targets: ['p1', 'p2', 'p3', 'p9'],
      screen: { t1: 'BUILD BACK' },
      hear: '聲音一層一層疊回來',
      note: {
        kind: 'win',
        title: '第 3 課完成',
        body: '光靠靜音，一段循環就能撐三分鐘。這是最被低估的演出工具。',
      },
    },
  ],
};
