import type { Lesson } from '@/types/lesson';

export const s5_02: Lesson = {
  id: 's5-02',
  slug: 'sequence-mode-live',
  season: 5,
  index: 2,
  title: 'Sequence Mode 當骨架',
  outcome: '一套你閉著眼睛也切得到的序列配置',
  minutes: 20,
  chapters: ['亮暗就是地圖', '切換序列', 'Bank 的記憶法'],
  needsComputer: false,
  firmwareVerified: '1.3.0',
  verifiedDate: '2026-08-08',
  prerequisites: ['s5-01'],
  sources: [
    'Akai 官方使用手冊 v1.3.0 (RevA)：Sequence Mode 中有內容的 pad 亮、空的暗；播放中按另一顆 pad 會閃亮綠代表排隊，等目前序列結束才切換；PAD BANK 按一下循環 A–H，按住它再按 PADS 1–8 可直接跳到該 Bank，目前 Bank 顯示在 MAIN VOLUME 旁',
    '演出配置建議為本站整理',
  ],
  checkpoints: [
    '你能從 pad 的亮暗看出哪些序列有內容',
    '你能不看螢幕切換到指定的序列',
    '你會用按住 PAD BANK 直接跳 Bank',
  ],
  steps: [
    {
      ch: 0,
      say: '按 <b>SEQ</b> 進 Sequence Mode。現在 pad 不發聲，是用來選段落的。',
      targets: ['seq'],
      screen: { t1: 'SEQ 01', tabs: ['Seq', 'BPM', 'Rec Q'] },
      hear: '—',
    },
    {
      ch: 0,
      say: '<b>亮的 pad 有內容，暗的是空的</b>。這就是你台上唯一需要的地圖。',
      targets: ['pads'],
      screen: { t1: 'SEQ  LIT = FILLED' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '台上不要看螢幕',
        body: '燈光暗、人在看你。練到能靠亮暗判斷，比記螢幕文字可靠。',
      },
    },
    {
      ch: 1,
      say: '播放中敲另一顆亮的 <b>pad</b>，它會<b>開始閃亮綠</b>，代表排隊中。',
      targets: ['p2'],
      screen: { t1: 'SEQ 02  QUEUED' },
      hear: '目前這段繼續播，還沒換',
      note: {
        kind: 'tip',
        title: '閃爍就是排隊',
        body: '正在播的那一顆是持續亮綠，排隊中的那一顆會閃。用燈就分得出來。',
      },
    },
    {
      ch: 1,
      say: '<b>等目前這段跑完，新的才會接上</b>。接上之後那顆 pad 就變成持續亮綠。',
      targets: ['p2'],
      screen: { t1: 'SEQ 02  ▶' },
      hear: '跑完一輪之後乾淨接到新段落',
      note: {
        kind: 'tip',
        title: '這是好消息',
        body: '你不會切在半路上。所以提早按沒關係，機器會幫你等到正確的時間點。',
      },
    },
    {
      ch: 1,
      say: '所以<b>要提早按</b>。想在第八小節換段，第七小節就先敲下去。',
      targets: ['p3'],
      screen: { t1: 'SEQ 03  QUEUED' },
      hear: '目前段落繼續，下一段排隊中',
    },
    {
      ch: 1,
      say: '練習方法：<b>只用兩段來回切二十次</b>。手先熟，再加第三段。',
      targets: ['p1', 'p2'],
      screen: { t1: 'SEQ 01 ↔ 02' },
      hear: '兩段來回接',
    },
    {
      ch: 2,
      say: '序列不夠用就換 Bank。按 <b>PAD BANK</b> 會依序循環 A 到 H。',
      targets: ['bank'],
      screen: { t1: 'BANK B' },
      hear: '—',
    },
    {
      ch: 2,
      say: '台上沒時間慢慢循環。<b>按住 PAD BANK 再按 PAD 1 到 8</b>，直接跳到那個 Bank。',
      targets: ['bank', 'p1', 'p2', 'p3'],
      screen: { t1: 'BANK C' },
      hear: '—',
      note: {
        kind: 'tip',
        title: '這一招很多人不知道',
        body: '按住 PAD BANK 再按 PAD 3 就是跳到 Bank C。比按三次快得多。',
      },
    },
    {
      ch: 2,
      say: '<b>目前在哪個 Bank，看面板上 MAIN VOLUME 旁邊那個字母</b>。不用看螢幕。',
      targets: ['vol', 'bank'],
      screen: { t1: 'BANK C' },
      hear: '—',
    },
    {
      ch: 2,
      say: '配置建議：<b>Bank A 放主要段落，Bank B 放過門與備援</b>。固定不要改。',
      targets: ['bank'],
      screen: { t1: 'A = MAIN   B = FILLS' },
      hear: '—',
      note: {
        kind: 'win',
        title: '第 2 課完成',
        body: '骨架有了。下一課用靜音在同一段序列裡做出變化。',
      },
    },
  ],
};
